= Open Identity Platform Documentation

== xref:opendj:ROOT:index.adoc[OpenDJ: Directory Services]

OpenDJ is an LDAPv3 compliant directory service, which has been developed for the Java platform and provides a high performance, 
highly available, and secure store for identities, that are managed by your organization. Its easy installation process, combined with 
the power of the Java platform makes OpenDJ the simplest, fastest directory to deploy and manage.

* xref:opendj:install-guide:index.adoc[]
* xref:opendj:admin-guide:index.adoc[]
* xref:opendj:server-dev-guide:index.adoc[]
* xref:opendj:reference:index.adoc[]


== xref:openam:ROOT:index.adoc[OpenAM: Access Management]

Open Access Management (OpenAM) is an access management solution that includes Authentication, SSO, Authorization, Federation, Entitlements, and Web Services Security.

* xref:openam:getting-started:index.adoc[]
* xref:openam:install-guide:index.adoc[]
* xref:openam:upgrade-guide:index.adoc[]
* xref:openam:admin-guide:index.adoc[]
* xref:openam:dev-guide:index.adoc[]
* xref:openam:deployment-planning:index.adoc[]
* xref:openam:reference:index.adoc[]
* xref:openam:web-users-guide:index.adoc[]
* xref:openam:jee-users-guide:index.adoc[]


== xref:openig:ROOT:index.adoc[OpenIG: Identity Gateway]

Open Identity Gateway (OpenIG) is a high-performance reverse proxy server with specialized session management 
and credential replay functionality.

* xref:openig:gateway-guide:index.adoc[]
* xref:openig:reference:index.adoc[]


== xref:openidm:ROOT:index.adoc[OpenIDM: Identity Management]

Open Identity Management (OpenIDM) is an open standards-based Identity Management, Provisioning, and Compliance solution. Provisioning users, devices, 
and things is a repetitive and potentially time-consuming task that has a significant impact on security and user access.

* xref:openidm:getting-started:index.adoc[]
* xref:openidm:install-guide:index.adoc[]
* xref:openidm:samples-guide:index.adoc[]
* xref:openidm:integrators-guide:index.adoc[]
* xref:openidm:connectors-guide:index.adoc[]
