////
The contents of this file are subject to the terms of the Common Development and
Distribution License (the License). You may not use this file except in compliance with the
License.

You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
specific language governing permission and limitations under the License.

When distributing Covered Software, include this CDDL Header Notice in each file and include
the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
Header, with the fields enclosed by brackets [] replaced by your own identifying
information: "Portions copyright [year] [name of copyright owner]".

Portions Copyright 2026 3A Systems, LLC.
////
= Open Identity Platform Documentation

== xref:opendj:ROOT:index.adoc[OpenDJ: Directory Services]

OpenDJ is an LDAPv3 compliant directory service, which has been developed for the Java platform and provides a high performance, 
highly available, and secure store for identities, that are managed by your organization. Its easy installation process, combined with 
the power of the Java platform makes OpenDJ the simplest, fastest directory to deploy and manage.

image:https://img.shields.io/github/v/release/OpenIdentityPlatform/OpenDJ?label=latest%20release[Latest OpenDJ release,link=https://github.com/OpenIdentityPlatform/OpenDJ/releases/latest]
link:https://github.com/OpenIdentityPlatform/OpenDJ/releases[Releases and downloads] ·
link:https://hub.docker.com/r/openidentityplatform/opendj[Docker images] ·
link:https://github.com/OpenIdentityPlatform/OpenDJ/security/advisories[Security advisories]

* xref:opendj:install-guide:index.adoc[]
* xref:opendj:admin-guide:index.adoc[]
* xref:opendj:server-dev-guide:index.adoc[]
* xref:opendj:reference:index.adoc[]
* link:/opendj/apidocs/index.html[API Reference (Javadoc)]


== xref:openam:ROOT:index.adoc[OpenAM: Access Management]

Open Access Management (OpenAM) is an access management solution that includes Authentication, SSO, Authorization, Federation, Entitlements, and Web Services Security.

image:https://img.shields.io/github/v/release/OpenIdentityPlatform/OpenAM?label=latest%20release[Latest OpenAM release,link=https://github.com/OpenIdentityPlatform/OpenAM/releases/latest]
link:https://github.com/OpenIdentityPlatform/OpenAM/releases[Releases and downloads] ·
link:https://hub.docker.com/r/openidentityplatform/openam[Docker images] ·
link:https://github.com/OpenIdentityPlatform/OpenAM/security/advisories[Security advisories]

* xref:openam:getting-started:index.adoc[]
* xref:openam:install-guide:index.adoc[]
* xref:openam:upgrade-guide:index.adoc[]
* xref:openam:admin-guide:index.adoc[]
* xref:openam:dev-guide:index.adoc[]
* xref:openam:deployment-planning:index.adoc[]
* xref:openam:reference:index.adoc[]
* xref:openam:web-users-guide:index.adoc[]
* xref:openam:jee-users-guide:index.adoc[]
* link:/openam/apidocs/index.html[API Reference (Javadoc)]


== xref:openig:ROOT:index.adoc[OpenIG: Identity Gateway]

Open Identity Gateway (OpenIG) is a high-performance reverse proxy server with specialized session management 
and credential replay functionality.

image:https://img.shields.io/github/v/release/OpenIdentityPlatform/OpenIG?label=latest%20release[Latest OpenIG release,link=https://github.com/OpenIdentityPlatform/OpenIG/releases/latest]
link:https://github.com/OpenIdentityPlatform/OpenIG/releases[Releases and downloads] ·
link:https://hub.docker.com/r/openidentityplatform/openig[Docker images]

* xref:openig:gateway-guide:index.adoc[]
* xref:openig:reference:index.adoc[]
* link:/openig/apidocs/index.html[API Reference (Javadoc)]


== xref:openidm:ROOT:index.adoc[OpenIDM: Identity Management]

Open Identity Management (OpenIDM) is an open standards-based Identity Management, Provisioning, and Compliance solution. Provisioning users, devices, 
and things is a repetitive and potentially time-consuming task that has a significant impact on security and user access.

image:https://img.shields.io/github/v/release/OpenIdentityPlatform/OpenIDM?label=latest%20release[Latest OpenIDM release,link=https://github.com/OpenIdentityPlatform/OpenIDM/releases/latest]
link:https://github.com/OpenIdentityPlatform/OpenIDM/releases[Releases and downloads] ·
link:https://hub.docker.com/r/openidentityplatform/openidm[Docker images] ·
link:https://github.com/OpenIdentityPlatform/OpenIDM/security/advisories[Security advisories]

* xref:openidm:getting-started:index.adoc[]
* xref:openidm:install-guide:index.adoc[]
* xref:openidm:samples-guide:index.adoc[]
* xref:openidm:integrators-guide:index.adoc[]
* xref:openidm:connectors-guide:index.adoc[]
* link:/openidm/apidocs/index.html[API Reference (Javadoc)]


[#api-reference]
== API Reference (Javadoc)

=== Products

* link:/opendj/apidocs/index.html[OpenDJ: Directory Services]
* link:/openam/apidocs/index.html[OpenAM: Access Management]
* link:/openig/apidocs/index.html[OpenIG: Identity Gateway]
* link:/openidm/apidocs/index.html[OpenIDM: Identity Management]

=== Libraries

* link:/openicf/apidocs/index.html[OpenICF] - the Open Identity Connectors Framework, which OpenIDM uses to connect to external resources
* link:/commons/apidocs/index.html[Commons] - libraries shared by the Open Identity Platform products
