site:
  title: Open Identity Platform Documentation
  start_page: ROOT::index.adoc
  url: https://doc.openidentityplatform.org
  robots: allow
  keys:
    google_analytics: 'G-TFFQQ60TMD'
    google_site_verification: 'gB-OZuT18mmNEL-k5UNMHmNWQX5Wv46GnWWs1XZxZeE'
content:
  edit_url: ~
  sources:
  - url: ./
    start_path: ROOT    
  - url: ./
    start_path: opendj
    edit_url: https://github.com/OpenIdentityPlatform/OpenDJ/edit/master/opendj-doc-generated-ref/src/main/asciidoc
  - url: ./
    start_path: openig
    edit_url: https://github.com/OpenIdentityPlatform/OpenIG/edit/master/openig-doc/src/main/asciidoc
  - url: ./
    start_path: openam
    edit_url: https://github.com/OpenIdentityPlatform/OpenAM/edit/master/openam-documentation/openam-doc-source/src/main/asciidoc
  - url: ./
    start_path: openidm
    edit_url: https://github.com/OpenIdentityPlatform/OpenIDM/edit/master/openidm-doc/src/main/asciidoc
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  clean: true

antora:
  extensions:
  - ./lib/add-pdf-link.js


asciidoc:
  extensions:
  - ./lib/nested-open-block
  attributes:
    page-toclevels: 1@
    page-pagination: ''

urls: 
  html_extension_style: drop 