////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

= Configuration Reference
:doctype: book
:toc:
:authors: Paul Bryan, Mark Craig, Jamie Nelson, Joanne Henry
:copyright: Copyright 2011-2017 ForgeRock AS.
:copyright: Portions Copyright 2024 3A Systems LLC.

:imagesdir: ../
:figure-caption!:
:example-caption!:
:table-caption!:
[abstract]
Reference documentation for OpenIG. OpenIG provides a high-performance reverse proxy server with specialized session management and credential replay functionality.

* xref:preface.adoc[]
* xref:required-conf.adoc[]
* xref:handlers-conf.adoc[]
* xref:filters-conf.adoc[]
* xref:decorators-conf.adoc[]
* xref:logging-conf.adoc[]
* xref:audit-conf.adoc[]
* xref:throttling-conf.adoc[]
* xref:misc-conf.adoc[]
* xref:expressions-conf.adoc[]
* xref:object-model-conf.adoc[]
* xref:appendix-interface-stability.adoc[]
