-
  name: 'OpenDJ'
  link: '/opendj'
  docs:
  - link: '/install-guide'
    description: OpenDJ Installation Guide
  - link: '/admin-guide'
    description: OpenDJ Administrators guide
  - link: '/dev-guide'
    description: OpenDJ Developer's Guide 
  - link: '/man-pages'
    description: OpenDJ Man Pages   
  
-
  name: 'OpenAM'
  link: '/openam'
  docs:
  - link: '/getting-started'
    description: Getting Started With OpenAM        
  - link: '/install-guide'
    description: OpenAM Installation Guide              
  - link: /admin-guide
    description: OpenAM Administrator's guide
  - link: '/reference'
    description: OpenAM Reference    
  - link: '/dev-guide'
    description: OpenAM Developer's Guide       
  - link: '/upgrade-guide'    
    description: OpenAM Upgrade Guide             
  - link: '/jee-install-guide'
    description: Java EE Policy Agent Installation Guide                
  - link: '/jee-reference'
    description: Java EE Policy Agent Reference        
  - link: '/web-install-guide'
    description: Web Policy Agent Installation Guide   
  - link: '/web-reference'
    description: Web Policy Agent Reference  
          
-
  name: 'OpenIG'
  link: '/openig'
  docs:
  - link: /gateway-guide
    description: Guide to OpenIG
  - link: /reference
    description: OpenIG Reference

-
  name: 'OpenIDM'
  link: '/openidm'
  docs:
  - link: /install-guide
    description: OpenIDM Installation Guide
  - link: /integrators-guide
    description: OpenIDM Integrator's Guide
  - link: /dev-guide
    description: OpenIDM Developer's Guide    
