////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

= Connectors Guide
:doctype: book
:toc:
:authors: Lana Frost
:copyright: Copyright 2011-2017 ForgeRock AS.
:copyright: Portions Copyright 2024 3A Systems LLC.

:imagesdir: ../
:figure-caption!:
:example-caption!:
:table-caption!:
:openidm-version: 7.0.1
:openidm-version-short: 6.2

[abstract]
This guide describes the connectors that are supported with OpenIDM {openidm-version-short}. The guide provides installation and configuration instructions for each connectors, and examples that demonstrate how to use the connectors in a deployment.

* xref:preface.adoc[]
* xref:chap-overview.adoc[]
* xref:chap-ldap.adoc[]
* xref:chap-csv.adoc[]
* xref:chap-database.adoc[]
* xref:chap-powershell.adoc[]
* xref:chap-groovy.adoc[]
* xref:chap-sap.adoc[]
* xref:chap-ssh.adoc[]
* xref:chap-google.adoc[]
* xref:chap-kerberos.adoc[]
* xref:chap-salesforce.adoc[]
* xref:chap-ad.adoc[]
* xref:chap-xml.adoc[]
* xref:appendix-interfaces.adoc[]
* xref:appendix-options.adoc[]
* xref:appendix-pooling.adoc[]
