////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

= Administration Guide
:doctype: book
:toc:
:authors: Mark Craig, Nemanja Lukić, Ludovic Poitou, Chris Ridd, Valery Kharseko
:copyright: Copyright 2011-2017 ForgeRock AS.
:copyright: Portions Copyright 2024 3A Systems LLC.

:imagesdir: ../
:figure-caption!:
:example-caption!:
:table-caption!:
[abstract]
Hands-on guide to configuring and using OpenDJ features. The OpenDJ project offers open source LDAP directory services in Java.

* xref:preface.adoc[]
* xref:chap-understanding-ldap.adoc[]
* xref:chap-admin-tools.adoc[]
* xref:chap-server-process.adoc[]
* xref:chap-import-export.adoc[]
* xref:chap-connection-handlers.adoc[]
* xref:chap-privileges-acis.adoc[]
* xref:chap-indexing.adoc[]
* xref:chap-replication.adoc[]
* xref:chap-backup-restore.adoc[]
* xref:chap-pwd-policy.adoc[]
* xref:chap-account-lockout.adoc[]
* xref:chap-resource-limits.adoc[]
* xref:chap-attribute-uniqueness.adoc[]
* xref:chap-schema.adoc[]
* xref:chap-pta.adoc[]
* xref:chap-samba.adoc[]
* xref:chap-monitoring.adoc[]
* xref:chap-tuning.adoc[]
* xref:chap-production.adoc[]
* xref:chap-change-certs.adoc[]
* xref:chap-mv-servers.adoc[]
* xref:chap-troubleshooting.adoc[]
