////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2025 3A Systems LLC.
////

[#dsconfig-set-password-generator-prop]
= dsconfig set-password-generator-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig set-password-generator-prop - Modifies Password Generator properties

== Synopsis

`dsconfig set-password-generator-prop` {options}

[#dsconfig-set-password-generator-prop-description]
== Description

Modifies Password Generator properties.



[#dsconfig-set-password-generator-prop-options]
== Options

The `dsconfig set-password-generator-prop` command takes the following options:

--
`--generator-name {name}`::

The name of the Password Generator.
+

[open]
====
Password Generator properties depend on the Password Generator type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Password Generator types:

`random-password-generator`::
+
Default {name}: Random Password Generator
+
Enabled by default: true
+
See  <<dsconfig-set-password-generator-prop-random-password-generator>> for the properties of this Password Generator type.
====

`--set {PROP:VALUE}`::

Assigns a value to a property where PROP is the name of the property and VALUE is the single value to be assigned. Specify the same property multiple times in order to assign more than one value to it.
+
Password Generator properties depend on the Password Generator type, which depends on the `--generator-name {name}` option.

`--reset {property}`::

Resets a property back to its default values where PROP is the name of the property to be reset.
+
Password Generator properties depend on the Password Generator type, which depends on the `--generator-name {name}` option.

`--add {PROP:VALUE}`::

Adds a single value to a property where PROP is the name of the property and VALUE is the single value to be added.
+
Password Generator properties depend on the Password Generator type, which depends on the `--generator-name {name}` option.

`--remove {PROP:VALUE}`::

Removes a single value from a property where PROP is the name of the property and VALUE is the single value to be removed.
+
Password Generator properties depend on the Password Generator type, which depends on the `--generator-name {name}` option.

--

[#dsconfig-set-password-generator-prop-random-password-generator]
== Random Password Generator

Password Generators of type random-password-generator have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Generator is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Random Password Generator implementation. 


Default Value::
org.opends.server.extensions.RandomPasswordGenerator


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordGenerator


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

password-character-set::
[open]
====
Description::
Specifies one or more named character sets. This is a multi-valued property, with each value defining a different character set. The format of the character set is the name of the set followed by a colon and the characters that are in that set. For example, the value &quot;alpha:abcdefghijklmnopqrstuvwxyz&quot; defines a character set named &quot;alpha&quot; containing all of the lower-case ASCII alphabetic characters.


Default Value::
None


Allowed Values::
A character set name (consisting of ASCII letters) followed by a colon and the set of characters that are included in that character set.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

password-format::
[open]
====
Description::
Specifies the format to use for the generated password. The value is a comma-delimited list of elements in which each of those elements is comprised of the name of a character set defined in the password-character-set property, a colon, and the number of characters to include from that set. For example, a value of &quot;alpha:3,numeric:2,alpha:3&quot; generates an 8-character password in which the first three characters are from the &quot;alpha&quot; set, the next two are from the &quot;numeric&quot; set, and the final three are from the &quot;alpha&quot; set.


Default Value::
None


Allowed Values::
A comma-delimited list whose elements comprise a valid character set name, a colon, and a positive integer indicating the number of characters from that set to be included.


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

