////
 # The contents of this file are subject to the terms of the Common Development and
 # Distribution License (the License). You may not use this file except in compliance with the
 # License.
 #
 # You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
 # specific language governing permission and limitations under the License.
 #
 # When distributing Covered Software, include this CDDL Header Notice in each file and include
 # the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 # Header, with the fields enclosed by brackets [] replaced by your own identifying
 # information: "Portions Copyright [year] [name of copyright owner]".
 #
 # Copyright 2015 ForgeRock AS.
 # Portions 2025 3A Systems LLC.
 #
////

[#base64-1]
= base64(1)

:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
base64 - encode and decode base64 strings

== Synopsis
`base64` `{subcommand} {options}`

[#base64-description]
== Description

This utility can be used to encode and decode information using base64.




[#base64-options]
== Options

The `base64` command takes the following options:


--
`-V | --version`::
Display Directory Server version information.
+
Default: false
+


--

--
`-H | --help`::
Display this usage information.
+
Default: false
+


--



[#base64-subcommands]
== Subcommands



The `base64` command supports the following subcommands:


[#base64-decode]
=== base64 decode

Decode base64-encoded information into raw data. When no options are specified, this subcommand reads from standard input and writes to standard output.



[#base64-decode-options]
==== Options

--

`-d | --encodedData {data}`::
The base64-encoded data to be decoded.
+

+

`-f | --encodedDataFile {path}`::
The path to a file containing the base64-encoded data to be decoded.
+

+

`-o | --toRawFile {path}`::
The path to a file to which the raw base64-decoded data should be written.
+

+


--




[#base64-encode]
=== base64 encode

Encode raw data using base64. When no options are specified, this subcommand reads from standard input and writes to standard output.



[#base64-encode-options]
==== Options

--

`-d | --rawData {data}`::
The raw data to be base64 encoded.
+

+

`-f | --rawDataFile {path}`::
The path to a file containing the raw data to be base64 encoded.
+

+

`-o | --toEncodedFile {path}`::
The path to a file to which the base64-encoded data should be written.
+

+


--





include::./_exit-codes-0-gt0.adoc[]

include::./_base64-examples.adoc[]


