////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2024-2026 3A Systems LLC.
////

[#dsconfig-set-alert-handler-prop]
= dsconfig set-alert-handler-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig set-alert-handler-prop - Modifies Alert Handler properties

== Synopsis

`dsconfig set-alert-handler-prop` {options}

[#dsconfig-set-alert-handler-prop-description]
== Description

Modifies Alert Handler properties.



[#dsconfig-set-alert-handler-prop-options]
== Options

The `dsconfig set-alert-handler-prop` command takes the following options:

--
`--handler-name {name}`::

The name of the Alert Handler.
+

[open]
====
Alert Handler properties depend on the Alert Handler type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Alert Handler types:

`jmx-alert-handler`::
+
Default {name}: JMX Alert Handler
+
Enabled by default: true
+
See  <<dsconfig-set-alert-handler-prop-jmx-alert-handler>> for the properties of this Alert Handler type.
`smtp-alert-handler`::
+
Default {name}: SMTP Alert Handler
+
Enabled by default: true
+
See  <<dsconfig-set-alert-handler-prop-smtp-alert-handler>> for the properties of this Alert Handler type.
====

`--set {PROP:VALUE}`::

Assigns a value to a property where PROP is the name of the property and VALUE is the single value to be assigned. Specify the same property multiple times in order to assign more than one value to it.
+
Alert Handler properties depend on the Alert Handler type, which depends on the `--handler-name {name}` option.

`--reset {property}`::

Resets a property back to its default values where PROP is the name of the property to be reset.
+
Alert Handler properties depend on the Alert Handler type, which depends on the `--handler-name {name}` option.

`--add {PROP:VALUE}`::

Adds a single value to a property where PROP is the name of the property and VALUE is the single value to be added.
+
Alert Handler properties depend on the Alert Handler type, which depends on the `--handler-name {name}` option.

`--remove {PROP:VALUE}`::

Removes a single value from a property where PROP is the name of the property and VALUE is the single value to be removed.
+
Alert Handler properties depend on the Alert Handler type, which depends on the `--handler-name {name}` option.

--

[#dsconfig-set-alert-handler-prop-jmx-alert-handler]
== JMX Alert Handler

Alert Handlers of type jmx-alert-handler have the following properties:

--


disabled-alert-type::
[open]
====
Description::
Specifies the names of the alert types that are disabled for this alert handler. If there are any values for this attribute, then no alerts with any of the specified types are allowed. If there are no values for this attribute, then only alerts with a type included in the set of enabled alert types are allowed, or if there are no values for the enabled alert types option, then all alert types are allowed.


Default Value::
If there is a set of enabled alert types, then only alerts with one of those types are allowed. Otherwise, all alerts are allowed.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the Alert Handler is enabled. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled-alert-type::
[open]
====
Description::
Specifies the names of the alert types that are enabled for this alert handler. If there are any values for this attribute, then only alerts with one of the specified types are allowed (unless they are also included in the disabled alert types). If there are no values for this attribute, then any alert with a type not included in the list of disabled alert types is allowed.


Default Value::
All alerts with types not included in the set of disabled alert types are allowed.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the JMX Alert Handler implementation. 


Default Value::
org.opends.server.extensions.JMXAlertHandler


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.AlertHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Alert Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-alert-handler-prop-smtp-alert-handler]
== SMTP Alert Handler

Alert Handlers of type smtp-alert-handler have the following properties:

--


disabled-alert-type::
[open]
====
Description::
Specifies the names of the alert types that are disabled for this alert handler. If there are any values for this attribute, then no alerts with any of the specified types are allowed. If there are no values for this attribute, then only alerts with a type included in the set of enabled alert types are allowed, or if there are no values for the enabled alert types option, then all alert types are allowed.


Default Value::
If there is a set of enabled alert types, then only alerts with one of those types are allowed. Otherwise, all alerts are allowed.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the Alert Handler is enabled. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled-alert-type::
[open]
====
Description::
Specifies the names of the alert types that are enabled for this alert handler. If there are any values for this attribute, then only alerts with one of the specified types are allowed (unless they are also included in the disabled alert types). If there are no values for this attribute, then any alert with a type not included in the list of disabled alert types is allowed.


Default Value::
All alerts with types not included in the set of disabled alert types are allowed.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the SMTP Alert Handler implementation. 


Default Value::
org.opends.server.extensions.SMTPAlertHandler


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.AlertHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Alert Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

message-body::
[open]
====
Description::
Specifies the body that should be used for email messages generated by this alert handler. The token &quot;%%%%alert-type%%%%&quot; is dynamically replaced with the alert type string. The token &quot;%%%%alert-id%%%%&quot; is dynamically replaced with the alert ID value. The token &quot;%%%%alert-message%%%%&quot; is dynamically replaced with the alert message. The token &quot;\n&quot; is replaced with an end-of-line marker.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

message-subject::
[open]
====
Description::
Specifies the subject that should be used for email messages generated by this alert handler. The token &quot;%%%%alert-type%%%%&quot; is dynamically replaced with the alert type string. The token &quot;%%%%alert-id%%%%&quot; is dynamically replaced with the alert ID value. The token &quot;%%%%alert-message%%%%&quot; is dynamically replaced with the alert message. The token &quot;\n&quot; is replaced with an end-of-line marker.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

recipient-address::
[open]
====
Description::
Specifies an email address to which the messages should be sent. Multiple values may be provided if there should be more than one recipient.


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

sender-address::
[open]
====
Description::
Specifies the email address to use as the sender for messages generated by this alert handler. 


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

