////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2024-2025 3A Systems LLC.
////

[#dsconfig-create-backend]
= dsconfig create-backend(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig create-backend - Creates Backends

== Synopsis

`dsconfig create-backend` {options}

[#dsconfig-create-backend-description]
== Description

Creates Backends.



[#dsconfig-create-backend-options]
== Options

The `dsconfig create-backend` command takes the following options:

--
`--backend-name {STRING}`::

The name of the new Backend which will also be used as the value of the "backend-id" property: Specifies a name to identify the associated backend.
+

[open]
====
Backend properties depend on the Backend type, which depends on the {STRING} you provide.

By default, OpenDJ directory server supports the following Backend types:

`backup-backend`::
+
Default {STRING}: Backup Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-backup-backend>> for the properties of this Backend type.
`cas-backend`::
+
Default {STRING}: CAS Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-cas-backend>> for the properties of this Backend type.
`jdbc-backend`::
+
Default {STRING}: JDBC Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-jdbc-backend>> for the properties of this Backend type.
`je-backend`::
+
Default {STRING}: JE Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-je-backend>> for the properties of this Backend type.
`ldif-backend`::
+
Default {STRING}: LDIF Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-ldif-backend>> for the properties of this Backend type.
`memory-backend`::
+
Default {STRING}: Memory Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-memory-backend>> for the properties of this Backend type.
`monitor-backend`::
+
Default {STRING}: Monitor Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-monitor-backend>> for the properties of this Backend type.
`null-backend`::
+
Default {STRING}: Null Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-null-backend>> for the properties of this Backend type.
`pdb-backend`::
+
Default {STRING}: PDB Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-pdb-backend>> for the properties of this Backend type.
`schema-backend`::
+
Default {STRING}: Schema Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-schema-backend>> for the properties of this Backend type.
`task-backend`::
+
Default {STRING}: Task Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-task-backend>> for the properties of this Backend type.
`trust-store-backend`::
+
Default {STRING}: Trust Store Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-trust-store-backend>> for the properties of this Backend type.
====

`--set {PROP:VALUE}`::

Assigns a value to a property where PROP is the name of the property and VALUE is the single value to be assigned. Specify the same property multiple times in order to assign more than one value to it.
+
Backend properties depend on the Backend type, which depends on the `--backend-name {STRING}` option.

`-t | --type {type}`::

The type of Backend which should be created. The value for TYPE can be one of: backup | cas | custom | custom-local | jdbc | je | ldif | memory | monitor | null | pdb | schema | task | trust-store.
+

[open]
====
Backend properties depend on the Backend type, which depends on the {type} you provide.

By default, OpenDJ directory server supports the following Backend types:

`backup-backend`::
+
Default {type}: Backup Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-backup-backend>> for the properties of this Backend type.
`cas-backend`::
+
Default {type}: CAS Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-cas-backend>> for the properties of this Backend type.
`jdbc-backend`::
+
Default {type}: JDBC Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-jdbc-backend>> for the properties of this Backend type.
`je-backend`::
+
Default {type}: JE Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-je-backend>> for the properties of this Backend type.
`ldif-backend`::
+
Default {type}: LDIF Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-ldif-backend>> for the properties of this Backend type.
`memory-backend`::
+
Default {type}: Memory Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-memory-backend>> for the properties of this Backend type.
`monitor-backend`::
+
Default {type}: Monitor Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-monitor-backend>> for the properties of this Backend type.
`null-backend`::
+
Default {type}: Null Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-null-backend>> for the properties of this Backend type.
`pdb-backend`::
+
Default {type}: PDB Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-pdb-backend>> for the properties of this Backend type.
`schema-backend`::
+
Default {type}: Schema Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-schema-backend>> for the properties of this Backend type.
`task-backend`::
+
Default {type}: Task Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-task-backend>> for the properties of this Backend type.
`trust-store-backend`::
+
Default {type}: Trust Store Backend
+
Enabled by default: true
+
See  <<dsconfig-create-backend-trust-store-backend>> for the properties of this Backend type.
====

--

[#dsconfig-create-backend-backup-backend]
== Backup Backend

Backends of type backup-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

backup-directory::
[open]
====
Description::
Specifies the path to a backup directory containing one or more backups for a particular backend. This is a multivalued property. Each value may specify a different backup directory if desired (one for each backend for which backups are taken). Values may be either absolute paths or paths that are relative to the base of the OpenDJ directory server installation.


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.BackupBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
disabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-create-backend-cas-backend]
== CAS Backend

Backends of type cas-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

cipher-key-length::
[open]
====
Description::
Specifies the key length in bits for the preferred cipher. 


Default Value::
128


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

cipher-transformation::
[open]
====
Description::
Specifies the cipher for the directory server. The syntax is &quot;algorithm/mode/padding&quot;. The full transformation is required: specifying only an algorithm and allowing the cipher provider to supply the default mode and padding is not supported, because there is no guarantee these default values are the same among different implementations. Some cipher algorithms, including RC4 and ARCFOUR, do not have a mode or padding, and hence must be specified using NONE for the mode field and NoPadding for the padding field. For example, RC4/NONE/NoPadding.


Default Value::
AES/CBC/PKCS5Padding


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

compact-encoding::
[open]
====
Description::
Indicates whether the backend should use a compact form when encoding entries by compressing the attribute descriptions and object class sets. Note that this property applies only to the entries themselves and does not impact the index data.


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
No

Read-only::
No


====

confidentiality-enabled::
[open]
====
Description::
Indicates whether the backend should make entries in database files readable only by Directory Server. Confidentiality is achieved by enrypting entries before writing them to the underlying storage. Entry encryption will protect data on disk from unauthorised parties reading the files; for complete protection, also set confidentiality for sensitive attributes indexes. The property cannot be set to false if some of the indexes have confidentiality set to true.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-directory::
[open]
====
Description::
Specifies the keyspace name The path may be either an absolute path or a path relative to the directory containing the base of the OpenDJ directory server installation. The path may be any valid directory path in which the server has appropriate permissions to read and write files and has sufficient space to hold the database contents.


Default Value::
ldap_opendj


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

entries-compressed::
[open]
====
Description::
Indicates whether the backend should attempt to compress entries before storing them in the database. Note that this property applies only to the entries themselves and does not impact the index data. Further, the effectiveness of the compression is based on the type of data contained in the entry.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

import-offheap-memory-size::
[open]
====
Description::
Specifies the amount of off-heap memory dedicated to the online operation (import-ldif, rebuild-index). 


Default Value::
Use only heap memory.


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-entry-limit::
[open]
====
Description::
Specifies the maximum number of entries that is allowed to match a given index key before that particular index key is no longer maintained. This property is analogous to the ALL IDs threshold in the Sun Java System Directory Server. Note that this is the default limit for the backend, and it may be overridden on a per-attribute basis.A value of 0 means there is no limit.


Default Value::
4000


Allowed Values::
An integer value. Lower value is 0. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneIf any index keys have already reached this limit, indexes need to be rebuilt before they are allowed to use the new limit.

Advanced Property::
No

Read-only::
No


====

index-filter-analyzer-enabled::
[open]
====
Description::
Indicates whether to gather statistical information about the search filters processed by the directory server while evaluating the usage of indexes. Analyzing indexes requires gathering search filter usage patterns from user requests, especially for values as specified in the filters and subsequently looking the status of those values into the index files. When a search requests is processed, internal or user generated, a first phase uses indexes to find potential entries to be returned. Depending on the search filter, if the index of one of the specified attributes matches too many entries (exceeds the index entry limit), the search becomes non-indexed. In any case, all entries thus gathered (or the entire DIT) are matched against the filter for actually returning the search result.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-filter-analyzer-max-filters::
[open]
====
Description::
The maximum number of search filter statistics to keep. When the maximum number of search filter is reached, the least used one will be deleted.


Default Value::
25


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.cassandra.Backend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

preload-time-limit::
[open]
====
Description::
Specifies the length of time that the backend is allowed to spend &quot;pre-loading&quot; data when it is initialized. The pre-load process is used to pre-populate the database cache, so that it can be more quickly available when the server is processing requests. A duration of zero means there is no pre-load.


Default Value::
0s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 0 milliseconds.Upper limit is 2147483647 milliseconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-jdbc-backend]
== JDBC Backend

Backends of type jdbc-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

cipher-key-length::
[open]
====
Description::
Specifies the key length in bits for the preferred cipher. 


Default Value::
128


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

cipher-transformation::
[open]
====
Description::
Specifies the cipher for the directory server. The syntax is &quot;algorithm/mode/padding&quot;. The full transformation is required: specifying only an algorithm and allowing the cipher provider to supply the default mode and padding is not supported, because there is no guarantee these default values are the same among different implementations. Some cipher algorithms, including RC4 and ARCFOUR, do not have a mode or padding, and hence must be specified using NONE for the mode field and NoPadding for the padding field. For example, RC4/NONE/NoPadding.


Default Value::
AES/CBC/PKCS5Padding


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

compact-encoding::
[open]
====
Description::
Indicates whether the backend should use a compact form when encoding entries by compressing the attribute descriptions and object class sets. Note that this property applies only to the entries themselves and does not impact the index data.


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
No

Read-only::
No


====

confidentiality-enabled::
[open]
====
Description::
Indicates whether the backend should make entries in database files readable only by Directory Server. Confidentiality is achieved by enrypting entries before writing them to the underlying storage. Entry encryption will protect data on disk from unauthorised parties reading the files; for complete protection, also set confidentiality for sensitive attributes indexes. The property cannot be set to false if some of the indexes have confidentiality set to true.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-directory::
[open]
====
Description::
Specifies the connection string jdbc:postgresql://localhost/test


Default Value::
jdbc:postgresql://localhost/test


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

entries-compressed::
[open]
====
Description::
Indicates whether the backend should attempt to compress entries before storing them in the database. Note that this property applies only to the entries themselves and does not impact the index data. Further, the effectiveness of the compression is based on the type of data contained in the entry.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

import-offheap-memory-size::
[open]
====
Description::
Specifies the amount of off-heap memory dedicated to the online operation (import-ldif, rebuild-index). 


Default Value::
Use only heap memory.


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-entry-limit::
[open]
====
Description::
Specifies the maximum number of entries that is allowed to match a given index key before that particular index key is no longer maintained. This property is analogous to the ALL IDs threshold in the Sun Java System Directory Server. Note that this is the default limit for the backend, and it may be overridden on a per-attribute basis.A value of 0 means there is no limit.


Default Value::
4000


Allowed Values::
An integer value. Lower value is 0. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneIf any index keys have already reached this limit, indexes need to be rebuilt before they are allowed to use the new limit.

Advanced Property::
No

Read-only::
No


====

index-filter-analyzer-enabled::
[open]
====
Description::
Indicates whether to gather statistical information about the search filters processed by the directory server while evaluating the usage of indexes. Analyzing indexes requires gathering search filter usage patterns from user requests, especially for values as specified in the filters and subsequently looking the status of those values into the index files. When a search requests is processed, internal or user generated, a first phase uses indexes to find potential entries to be returned. Depending on the search filter, if the index of one of the specified attributes matches too many entries (exceeds the index entry limit), the search becomes non-indexed. In any case, all entries thus gathered (or the entire DIT) are matched against the filter for actually returning the search result.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-filter-analyzer-max-filters::
[open]
====
Description::
The maximum number of search filter statistics to keep. When the maximum number of search filter is reached, the least used one will be deleted.


Default Value::
25


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.jdbc.Backend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

preload-time-limit::
[open]
====
Description::
Specifies the length of time that the backend is allowed to spend &quot;pre-loading&quot; data when it is initialized. The pre-load process is used to pre-populate the database cache, so that it can be more quickly available when the server is processing requests. A duration of zero means there is no pre-load.


Default Value::
0s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 0 milliseconds.Upper limit is 2147483647 milliseconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-je-backend]
== JE Backend

Backends of type je-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

cipher-key-length::
[open]
====
Description::
Specifies the key length in bits for the preferred cipher. 


Default Value::
128


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

cipher-transformation::
[open]
====
Description::
Specifies the cipher for the directory server. The syntax is &quot;algorithm/mode/padding&quot;. The full transformation is required: specifying only an algorithm and allowing the cipher provider to supply the default mode and padding is not supported, because there is no guarantee these default values are the same among different implementations. Some cipher algorithms, including RC4 and ARCFOUR, do not have a mode or padding, and hence must be specified using NONE for the mode field and NoPadding for the padding field. For example, RC4/NONE/NoPadding.


Default Value::
AES/CBC/PKCS5Padding


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

compact-encoding::
[open]
====
Description::
Indicates whether the backend should use a compact form when encoding entries by compressing the attribute descriptions and object class sets. Note that this property applies only to the entries themselves and does not impact the index data.


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
No

Read-only::
No


====

confidentiality-enabled::
[open]
====
Description::
Indicates whether the backend should make entries in database files readable only by Directory Server. Confidentiality is achieved by enrypting entries before writing them to the underlying storage. Entry encryption will protect data on disk from unauthorised parties reading the files; for complete protection, also set confidentiality for sensitive attributes indexes. The property cannot be set to false if some of the indexes have confidentiality set to true.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-cache-percent::
[open]
====
Description::
Specifies the percentage of JVM memory to allocate to the database cache. Specifies the percentage of memory available to the JVM that should be used for caching database contents. Note that this is only used if the value of the db-cache-size property is set to &quot;0 MB&quot;. Otherwise, the value of that property is used instead to control the cache size configuration.


Default Value::
50


Allowed Values::
An integer value. Lower value is 1. Upper value is 90.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-cache-size::
[open]
====
Description::
The amount of JVM memory to allocate to the database cache. Specifies the amount of memory that should be used for caching database contents. A value of &quot;0 MB&quot; indicates that the db-cache-percent property should be used instead to specify the cache size.


Default Value::
0 MB


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-checkpointer-bytes-interval::
[open]
====
Description::
Specifies the maximum number of bytes that may be written to the database before it is forced to perform a checkpoint. This can be used to bound the recovery time that may be required if the database environment is opened without having been properly closed. If this property is set to a non-zero value, the checkpointer wakeup interval is not used. To use time-based checkpointing, set this property to zero.


Default Value::
500mb


Allowed Values::
Upper value is 9223372036854775807.


Multi-valued::
No

Required::
No

Admin Action Required::
Restart the server

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-checkpointer-wakeup-interval::
[open]
====
Description::
Specifies the maximum length of time that may pass between checkpoints. Note that this is only used if the value of the checkpointer bytes interval is zero.


Default Value::
30s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 1 seconds.Upper limit is 4294 seconds.


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-cleaner-min-utilization::
[open]
====
Description::
Specifies the occupancy percentage for &quot;live&quot; data in this backend&apos;s database. When the amount of &quot;live&quot; data in the database drops below this value, cleaners will act to increase the occupancy percentage by compacting the database.


Default Value::
50


Allowed Values::
An integer value. Lower value is 0. Upper value is 90.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-directory::
[open]
====
Description::
Specifies the path to the filesystem directory that is used to hold the Berkeley DB Java Edition database files containing the data for this backend. The path may be either an absolute path or a path relative to the directory containing the base of the OpenDJ directory server installation. The path may be any valid directory path in which the server has appropriate permissions to read and write files and has sufficient space to hold the database contents.


Default Value::
db


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

db-directory-permissions::
[open]
====
Description::
Specifies the permissions that should be applied to the directory containing the server database files. They should be expressed as three-digit octal values, which is the traditional representation for UNIX file permissions. The three digits represent the permissions that are available for the directory&apos;s owner, group members, and other users (in that order), and each digit is the octal representation of the read, write, and execute bits. Note that this only impacts permissions on the database directory and not on the files written into that directory. On UNIX systems, the user&apos;s umask controls permissions given to the database files.


Default Value::
700


Allowed Values::
Any octal value between 700 and 777 (the owner must always have read, write, and execute permissions on the directory).


Multi-valued::
No

Required::
No

Admin Action Required::
Restart the server

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-evictor-core-threads::
[open]
====
Description::
Specifies the core number of threads in the eviction thread pool. Specifies the core number of threads in the eviction thread pool. These threads help keep memory usage within cache bounds, offloading work from application threads. db-evictor-core-threads, db-evictor-max-threads and db-evictor-keep-alive are used to configure the core, max and keepalive attributes for the eviction thread pool.


Default Value::
1


Allowed Values::
An integer value. Lower value is 0. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-evictor-keep-alive::
[open]
====
Description::
The duration that excess threads in the eviction thread pool will stay idle. After this period, idle threads will terminate. The duration that excess threads in the eviction thread pool will stay idle. After this period, idle threads will terminate. db-evictor-core-threads, db-evictor-max-threads and db-evictor-keep-alive are used to configure the core, max and keepalive attributes for the eviction thread pool.


Default Value::
600s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 1 seconds.Upper limit is 86400 seconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-evictor-lru-only::
[open]
====
Description::
Indicates whether the database should evict existing data from the cache based on an LRU policy (where the least recently used information will be evicted first). If set to &quot;false&quot;, then the eviction keeps internal nodes of the underlying Btree in the cache over leaf nodes, even if the leaf nodes have been accessed more recently. This may be a better configuration for databases in which only a very small portion of the data is cached.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-evictor-max-threads::
[open]
====
Description::
Specifies the maximum number of threads in the eviction thread pool. Specifies the maximum number of threads in the eviction thread pool. These threads help keep memory usage within cache bounds, offloading work from application threads. db-evictor-core-threads, db-evictor-max-threads and db-evictor-keep-alive are used to configure the core, max and keepalive attributes for the eviction thread pool.


Default Value::
10


Allowed Values::
An integer value. Lower value is 1. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-evictor-nodes-per-scan::
[open]
====
Description::
Specifies the number of Btree nodes that should be evicted from the cache in a single pass if it is determined that it is necessary to free existing data in order to make room for new information. Changes to this property do not take effect until the backend is restarted. It is recommended that you also change this property when you set db-evictor-lru-only to false. This setting controls the number of Btree nodes that are considered, or sampled, each time a node is evicted. A setting of 10 often produces good results, but this may vary from application to application. The larger the nodes per scan, the more accurate the algorithm. However, don&apos;t set it too high. When considering larger numbers of nodes for each eviction, the evictor may delay the completion of a given database operation, which impacts the response time of the application thread. In JE 4.1 and later, setting this value too high in an application that is largely CPU bound can reduce the effectiveness of cache eviction. It&apos;s best to start with the default value, and increase it gradually to see if it is beneficial for your application.


Default Value::
10


Allowed Values::
An integer value. Lower value is 1. Upper value is 1000.


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-log-file-max::
[open]
====
Description::
Specifies the maximum size for a database log file. 


Default Value::
100mb


Allowed Values::
Lower value is 1000000.Upper value is 4294967296.


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-log-filecache-size::
[open]
====
Description::
Specifies the size of the file handle cache. The file handle cache is used to keep as much opened log files as possible. When the cache is smaller than the number of logs, the database needs to close some handles and open log files it needs, resulting in less optimal performances. Ideally, the size of the cache should be higher than the number of files contained in the database. Make sure the OS number of open files per process is also tuned appropriately.


Default Value::
100


Allowed Values::
An integer value. Lower value is 3. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-logging-file-handler-on::
[open]
====
Description::
Indicates whether the database should maintain a je.info file in the same directory as the database log directory. This file contains information about the internal processing performed by the underlying database.


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-logging-level::
[open]
====
Description::
Specifies the log level that should be used by the database when it is writing information into the je.info file. The database trace logging level is (in increasing order of verbosity) chosen from: OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL.


Default Value::
CONFIG


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-num-cleaner-threads::
[open]
====
Description::
Specifies the number of threads that the backend should maintain to keep the database log files at or near the desired utilization. In environments with high write throughput, multiple cleaner threads may be required to maintain the desired utilization.


Default Value::
Let the server decide.


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-num-lock-tables::
[open]
====
Description::
Specifies the number of lock tables that are used by the underlying database. This can be particularly important to help improve scalability by avoiding contention on systems with large numbers of CPUs. The value of this configuration property should be set to a prime number that is less than or equal to the number of worker threads configured for use in the server.


Default Value::
Let the server decide.


Allowed Values::
An integer value. Lower value is 1. Upper value is 32767.


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-run-cleaner::
[open]
====
Description::
Indicates whether the cleaner threads should be enabled to compact the database. The cleaner threads are used to periodically compact the database when it reaches a percentage of occupancy lower than the amount specified by the db-cleaner-min-utilization property. They identify database files with a low percentage of live data, and relocate their remaining live data to the end of the log.


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-txn-no-sync::
[open]
====
Description::
Indicates whether database writes should be primarily written to an internal buffer but not immediately written to disk. Setting the value of this configuration attribute to &quot;true&quot; may improve write performance but could cause the most recent changes to be lost if the OpenDJ directory server or the underlying JVM exits abnormally, or if an OS or hardware failure occurs (a behavior similar to running with transaction durability disabled in the Sun Java System Directory Server).


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-txn-write-no-sync::
[open]
====
Description::
Indicates whether the database should synchronously flush data as it is written to disk. If this value is set to &quot;false&quot;, then all data written to disk is synchronously flushed to persistent storage and thereby providing full durability. If it is set to &quot;true&quot;, then data may be cached for a period of time by the underlying operating system before actually being written to disk. This may improve performance, but could cause the most recent changes to be lost in the event of an underlying OS or hardware failure (but not in the case that the OpenDJ directory server or the JVM exits abnormally).


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

disk-full-threshold::
[open]
====
Description::
Full disk threshold to limit database updates When the available free space on the disk used by this database instance falls below the value specified, no updates are permitted and the server returns an UNWILLING_TO_PERFORM error. Updates are allowed again as soon as free space rises above the threshold.


Default Value::
100 megabytes


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

disk-low-threshold::
[open]
====
Description::
Low disk threshold to limit database updates Specifies the &quot;low&quot; free space on the disk. When the available free space on the disk used by this database instance falls below the value specified, protocol updates on this database are permitted only by a user with the BYPASS_LOCKDOWN privilege.


Default Value::
200 megabytes


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

entries-compressed::
[open]
====
Description::
Indicates whether the backend should attempt to compress entries before storing them in the database. Note that this property applies only to the entries themselves and does not impact the index data. Further, the effectiveness of the compression is based on the type of data contained in the entry.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

import-offheap-memory-size::
[open]
====
Description::
Specifies the amount of off-heap memory dedicated to the online operation (import-ldif, rebuild-index). 


Default Value::
Use only heap memory.


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-entry-limit::
[open]
====
Description::
Specifies the maximum number of entries that is allowed to match a given index key before that particular index key is no longer maintained. This property is analogous to the ALL IDs threshold in the Sun Java System Directory Server. Note that this is the default limit for the backend, and it may be overridden on a per-attribute basis.A value of 0 means there is no limit.


Default Value::
4000


Allowed Values::
An integer value. Lower value is 0. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneIf any index keys have already reached this limit, indexes need to be rebuilt before they are allowed to use the new limit.

Advanced Property::
No

Read-only::
No


====

index-filter-analyzer-enabled::
[open]
====
Description::
Indicates whether to gather statistical information about the search filters processed by the directory server while evaluating the usage of indexes. Analyzing indexes requires gathering search filter usage patterns from user requests, especially for values as specified in the filters and subsequently looking the status of those values into the index files. When a search requests is processed, internal or user generated, a first phase uses indexes to find potential entries to be returned. Depending on the search filter, if the index of one of the specified attributes matches too many entries (exceeds the index entry limit), the search becomes non-indexed. In any case, all entries thus gathered (or the entire DIT) are matched against the filter for actually returning the search result.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-filter-analyzer-max-filters::
[open]
====
Description::
The maximum number of search filter statistics to keep. When the maximum number of search filter is reached, the least used one will be deleted.


Default Value::
25


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.jeb.JEBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

je-property::
[open]
====
Description::
Specifies the database and environment properties for the Berkeley DB Java Edition database serving the data for this backend. Any Berkeley DB Java Edition property can be specified using the following form: property-name=property-value. Refer to OpenDJ documentation for further information on related properties, their implications, and range values. The definitive identification of all the property parameters is available in the example.properties file of Berkeley DB Java Edition distribution.


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

preload-time-limit::
[open]
====
Description::
Specifies the length of time that the backend is allowed to spend &quot;pre-loading&quot; data when it is initialized. The pre-load process is used to pre-populate the database cache, so that it can be more quickly available when the server is processing requests. A duration of zero means there is no pre-load.


Default Value::
0s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 0 milliseconds.Upper limit is 2147483647 milliseconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-ldif-backend]
== LDIF Backend

Backends of type ldif-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

is-private-backend::
[open]
====
Description::
Indicates whether the backend should be considered a private backend, which indicates that it is used for storing operational data rather than user-defined information. 


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.LDIFBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

ldif-file::
[open]
====
Description::
Specifies the path to the LDIF file containing the data for this backend. 


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-memory-backend]
== Memory Backend

Backends of type memory-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.MemoryBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-monitor-backend]
== Monitor Backend

Backends of type monitor-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.MonitorBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
disabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-null-backend]
== Null Backend

Backends of type null-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.NullBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-pdb-backend]
== PDB Backend

Backends of type pdb-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

cipher-key-length::
[open]
====
Description::
Specifies the key length in bits for the preferred cipher. 


Default Value::
128


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

cipher-transformation::
[open]
====
Description::
Specifies the cipher for the directory server. The syntax is &quot;algorithm/mode/padding&quot;. The full transformation is required: specifying only an algorithm and allowing the cipher provider to supply the default mode and padding is not supported, because there is no guarantee these default values are the same among different implementations. Some cipher algorithms, including RC4 and ARCFOUR, do not have a mode or padding, and hence must be specified using NONE for the mode field and NoPadding for the padding field. For example, RC4/NONE/NoPadding.


Default Value::
AES/CBC/PKCS5Padding


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

compact-encoding::
[open]
====
Description::
Indicates whether the backend should use a compact form when encoding entries by compressing the attribute descriptions and object class sets. Note that this property applies only to the entries themselves and does not impact the index data.


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
No

Read-only::
No


====

confidentiality-enabled::
[open]
====
Description::
Indicates whether the backend should make entries in database files readable only by Directory Server. Confidentiality is achieved by enrypting entries before writing them to the underlying storage. Entry encryption will protect data on disk from unauthorised parties reading the files; for complete protection, also set confidentiality for sensitive attributes indexes. The property cannot be set to false if some of the indexes have confidentiality set to true.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-cache-percent::
[open]
====
Description::
Specifies the percentage of JVM memory to allocate to the database cache. Specifies the percentage of memory available to the JVM that should be used for caching database contents. Note that this is only used if the value of the db-cache-size property is set to &quot;0 MB&quot;. Otherwise, the value of that property is used instead to control the cache size configuration.


Default Value::
50


Allowed Values::
An integer value. Lower value is 1. Upper value is 90.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-cache-size::
[open]
====
Description::
The amount of JVM memory to allocate to the database cache. Specifies the amount of memory that should be used for caching database contents. A value of &quot;0 MB&quot; indicates that the db-cache-percent property should be used instead to specify the cache size.


Default Value::
0 MB


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

db-checkpointer-wakeup-interval::
[open]
====
Description::
Specifies the maximum length of time that may pass between checkpoints. This setting controls the elapsed time between attempts to write a checkpoint to the journal. A longer interval allows more updates to accumulate in buffers before they are required to be written to disk, but also potentially causes recovery from an abrupt termination (crash) to take more time.


Default Value::
15s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 10 seconds.Upper limit is 3600 seconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-directory::
[open]
====
Description::
Specifies the path to the filesystem directory that is used to hold the Persistit database files containing the data for this backend. The path may be either an absolute path or a path relative to the directory containing the base of the OpenDJ directory server installation. The path may be any valid directory path in which the server has appropriate permissions to read and write files and has sufficient space to hold the database contents.


Default Value::
db


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

db-directory-permissions::
[open]
====
Description::
Specifies the permissions that should be applied to the directory containing the server database files. They should be expressed as three-digit octal values, which is the traditional representation for UNIX file permissions. The three digits represent the permissions that are available for the directory&apos;s owner, group members, and other users (in that order), and each digit is the octal representation of the read, write, and execute bits. Note that this only impacts permissions on the database directory and not on the files written into that directory. On UNIX systems, the user&apos;s umask controls permissions given to the database files.


Default Value::
700


Allowed Values::
Any octal value between 700 and 777 (the owner must always have read, write, and execute permissions on the directory).


Multi-valued::
No

Required::
No

Admin Action Required::
Restart the server

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

db-txn-no-sync::
[open]
====
Description::
Indicates whether database writes should be primarily written to an internal buffer but not immediately written to disk. Setting the value of this configuration attribute to &quot;true&quot; may improve write performance but could cause the most recent changes to be lost if the OpenDJ directory server or the underlying JVM exits abnormally, or if an OS or hardware failure occurs (a behavior similar to running with transaction durability disabled in the Sun Java System Directory Server).


Default Value::
true


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

disk-full-threshold::
[open]
====
Description::
Full disk threshold to limit database updates When the available free space on the disk used by this database instance falls below the value specified, no updates are permitted and the server returns an UNWILLING_TO_PERFORM error. Updates are allowed again as soon as free space rises above the threshold.


Default Value::
100 megabytes


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

disk-low-threshold::
[open]
====
Description::
Low disk threshold to limit database updates Specifies the &quot;low&quot; free space on the disk. When the available free space on the disk used by this database instance falls below the value specified, protocol updates on this database are permitted only by a user with the BYPASS_LOCKDOWN privilege.


Default Value::
200 megabytes


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

entries-compressed::
[open]
====
Description::
Indicates whether the backend should attempt to compress entries before storing them in the database. Note that this property applies only to the entries themselves and does not impact the index data. Further, the effectiveness of the compression is based on the type of data contained in the entry.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this setting take effect only for writes that occur after the change is made. It is not retroactively applied to existing data.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

import-offheap-memory-size::
[open]
====
Description::
Specifies the amount of off-heap memory dedicated to the online operation (import-ldif, rebuild-index). 


Default Value::
Use only heap memory.


Allowed Values::



Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-entry-limit::
[open]
====
Description::
Specifies the maximum number of entries that is allowed to match a given index key before that particular index key is no longer maintained. This property is analogous to the ALL IDs threshold in the Sun Java System Directory Server. Note that this is the default limit for the backend, and it may be overridden on a per-attribute basis.A value of 0 means there is no limit.


Default Value::
4000


Allowed Values::
An integer value. Lower value is 0. Upper value is 2147483647.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneIf any index keys have already reached this limit, indexes need to be rebuilt before they are allowed to use the new limit.

Advanced Property::
No

Read-only::
No


====

index-filter-analyzer-enabled::
[open]
====
Description::
Indicates whether to gather statistical information about the search filters processed by the directory server while evaluating the usage of indexes. Analyzing indexes requires gathering search filter usage patterns from user requests, especially for values as specified in the filters and subsequently looking the status of those values into the index files. When a search requests is processed, internal or user generated, a first phase uses indexes to find potential entries to be returned. Depending on the search filter, if the index of one of the specified attributes matches too many entries (exceeds the index entry limit), the search becomes non-indexed. In any case, all entries thus gathered (or the entire DIT) are matched against the filter for actually returning the search result.


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

index-filter-analyzer-max-filters::
[open]
====
Description::
The maximum number of search filter statistics to keep. When the maximum number of search filter is reached, the least used one will be deleted.


Default Value::
25


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.pdb.PDBBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

preload-time-limit::
[open]
====
Description::
Specifies the length of time that the backend is allowed to spend &quot;pre-loading&quot; data when it is initialized. The pre-load process is used to pre-populate the database cache, so that it can be more quickly available when the server is processing requests. A duration of zero means there is no pre-load.


Default Value::
0s


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 0 milliseconds.Upper limit is 2147483647 milliseconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-schema-backend]
== Schema Backend

Backends of type schema-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.SchemaBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

schema-entry-dn::
[open]
====
Description::
Defines the base DNs of the subtrees in which the schema information is published in addition to the value included in the base-dn property. The value provided in the base-dn property is the only one that appears in the subschemaSubentry operational attribute of the server&apos;s root DSE (which is necessary because that is a single-valued attribute) and as a virtual attribute in other entries. The schema-entry-dn attribute may be used to make the schema information available in other locations to accommodate certain client applications that have been hard-coded to expect the schema to reside in a specific location.


Default Value::
cn=schema


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

show-all-attributes::
[open]
====
Description::
Indicates whether to treat all attributes in the schema entry as if they were user attributes regardless of their configuration. This may provide compatibility with some applications that expect schema attributes like attributeTypes and objectClasses to be included by default even if they are not requested. Note that the ldapSyntaxes attribute is always treated as operational in order to avoid problems with attempts to modify the schema over protocol.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-task-backend]
== Task Backend

Backends of type task-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.task.TaskBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

notification-sender-address::
[open]
====
Description::
Specifies the email address to use as the sender (that is, the &quot;From:&quot; address) address for notification mail messages generated when a task completes execution. 


Default Value::
The default sender address used is "opendj-task-notification@" followed by the canonical address of the system on which the server is running.


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

task-backing-file::
[open]
====
Description::
Specifies the path to the backing file for storing information about the tasks configured in the server. It may be either an absolute path or a relative path to the base of the OpenDJ directory server instance.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

task-retention-time::
[open]
====
Description::
Specifies the length of time that task entries should be retained after processing on the associated task has been completed. 


Default Value::
24 hours


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 0 seconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-create-backend-trust-store-backend]
== Trust Store Backend

Backends of type trust-store-backend have the following properties:

--


backend-id::
[open]
====
Description::
Specifies a name to identify the associated backend. The name must be unique among all backends in the server. The backend ID may not be altered after the backend is created in the server.


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
Yes


====

base-dn::
[open]
====
Description::
Specifies the base DN(s) for the data that the backend handles. A single backend may be responsible for one or more base DNs. Note that no two backends may have the same base DN although one backend may have a base DN that is below a base DN provided by another backend (similar to the use of sub-suffixes in the Sun Java System Directory Server). If any of the base DNs is subordinate to a base DN for another backend, then all base DNs for that backend must be subordinate to that same base DN.


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
Yes

Admin Action Required::
NoneNo administrative action is required by default although some action may be required on a per-backend basis before the new base DN may be used.

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the backend is enabled in the server. If a backend is not enabled, then its contents are not accessible when processing operations.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the backend implementation. 


Default Value::
org.opends.server.backends.TrustStoreBackend


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.Backend


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Backend must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

trust-store-file::
[open]
====
Description::
Specifies the path to the file that stores the trust information. It may be an absolute path, or a path that is relative to the OpenDJ instance root.


Default Value::
config/ads-truststore


Allowed Values::
A String


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

trust-store-pin::
[open]
====
Description::
Specifies the clear-text PIN needed to access the Trust Store Backend . 


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property will take effect the next time that the Trust Store Backend is accessed.

Advanced Property::
No

Read-only::
No


====

trust-store-pin-environment-variable::
[open]
====
Description::
Specifies the name of the environment variable that contains the clear-text PIN needed to access the Trust Store Backend . 


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property will take effect the next time that the Trust Store Backend is accessed.

Advanced Property::
No

Read-only::
No


====

trust-store-pin-file::
[open]
====
Description::
Specifies the path to the text file whose only contents should be a single line containing the clear-text PIN needed to access the Trust Store Backend . 


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property will take effect the next time that the Trust Store Backend is accessed.

Advanced Property::
No

Read-only::
No


====

trust-store-pin-property::
[open]
====
Description::
Specifies the name of the Java property that contains the clear-text PIN needed to access the Trust Store Backend . 


Default Value::
None


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property will take effect the next time that the Trust Store Backend is accessed.

Advanced Property::
No

Read-only::
No


====

trust-store-type::
[open]
====
Description::
Specifies the format for the data in the key store file. Valid values should always include &apos;JKS&apos; and &apos;PKCS12&apos;, but different implementations may allow other values as well.


Default Value::
The JVM default value is used.


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect the next time that the key manager is accessed.

Advanced Property::
No

Read-only::
No


====

writability-mode::
[open]
====
Description::
Specifies the behavior that the backend should use when processing write operations. 


Default Value::
enabled


Allowed Values::


disabled::
Causes all write attempts to fail.

enabled::
Allows write operations to be performed in that backend (if the requested operation is valid, the user has permission to perform the operation, the backend supports that type of write operation, and the global writability-mode property is also enabled).

internal-only::
Causes external write attempts to fail but allows writes by replication and internal operations.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

