////
 # The contents of this file are subject to the terms of the Common Development and
 # Distribution License (the License). You may not use this file except in compliance with the
 # License.
 #
 # You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
 # specific language governing permission and limitations under the License.
 #
 # When distributing Covered Software, include this CDDL Header Notice in each file and include
 # the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 # Header, with the fields enclosed by brackets [] replaced by your own identifying
 # information: "Portions Copyright [year] [name of copyright owner]".
 #
 # Copyright 2015 ForgeRock AS.
 # Portions Copyright 2024-2025 3A Systems LLC.
 #
////

[#upgrade-1]
= upgrade(1)

:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
upgrade - upgrade OpenDJ configuration and application data

== Synopsis
`upgrade` `{options}`

[#upgrade-description]
== Description

Upgrades OpenDJ configuration and application data so that it is compatible with the installed binaries.

This tool should be run immediately after upgrading the OpenDJ binaries and before restarting the server.

NOTE: this tool does not provide backup or restore capabilities. Therefore, it is the responsibility of the OpenDJ administrator to take necessary precautions before performing the upgrade.

<xinclude:include href="description-upgrade.xml" />


[#upgrade-options]
== Options

The `upgrade` command takes the following options:

.Command options:

--
`--acceptLicense`::
Automatically accepts the product license (if present).
+
Default: false
+

`--force`::
Forces a non-interactive upgrade to continue even if it requires user interaction. In particular, long running or critical upgrade tasks, such as re-indexing, which require user confirmation will be skipped. This option may only be used with the 'no-prompt' option.
+
Default: false
+

`--ignoreErrors`::
Ignores any errors which occur during the upgrade. This option should be used with caution and may be useful in automated deployments where potential errors are known in advance and resolved after the upgrade has completed.
+
Default: false
+


--
.Utility input/output options:

--
`-n | --no-prompt`::
Use non-interactive mode.  If data in the command is missing, the user is not prompted and the tool will fail.
+
Default: false
+

`-Q | --quiet`::
Use quiet mode.
+
Default: false
+

`-v | --verbose`::
Use verbose mode.
+
Default: false
+


--
.General options:

--
`-V | --version`::
Display Directory Server version information.
+
Default: false
+


--

--
`-H | --help`::
Display this usage information.
+
Default: false
+


--




include::./_upgrade-exit-codes.adoc[]


