////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

[#dsconfig-set-extended-operation-handler-prop]
= dsconfig set-extended-operation-handler-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig set-extended-operation-handler-prop - Modifies Extended Operation Handler properties

== Synopsis

`dsconfig set-extended-operation-handler-prop` {options}

[#dsconfig-set-extended-operation-handler-prop-description]
== Description

Modifies Extended Operation Handler properties.



[#dsconfig-set-extended-operation-handler-prop-options]
== Options

The `dsconfig set-extended-operation-handler-prop` command takes the following options:

--
`--handler-name {name}`::

The name of the Extended Operation Handler.
+

[open]
====
Extended Operation Handler properties depend on the Extended Operation Handler type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Extended Operation Handler types:

`cancel-extended-operation-handler`::
+
Default {name}: Cancel Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-cancel-extended-operation-handler>> for the properties of this Extended Operation Handler type.
`get-connection-id-extended-operation-handler`::
+
Default {name}: Get Connection Id Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-get-connection-id-extended-operation-handler>> for the properties of this Extended Operation Handler type.
`get-symmetric-key-extended-operation-handler`::
+
Default {name}: Get Symmetric Key Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-get-symmetric-key-extended-operation-handler>> for the properties of this Extended Operation Handler type.
`password-modify-extended-operation-handler`::
+
Default {name}: Password Modify Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-password-modify-extended-operation-handler>> for the properties of this Extended Operation Handler type.
`password-policy-state-extended-operation-handler`::
+
Default {name}: Password Policy State Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-password-policy-state-extended-operation-handler>> for the properties of this Extended Operation Handler type.
`start-tls-extended-operation-handler`::
+
Default {name}: Start TLS Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-start-tls-extended-operation-handler>> for the properties of this Extended Operation Handler type.
`who-am-i-extended-operation-handler`::
+
Default {name}: Who Am I Extended Operation Handler
+
Enabled by default: true
+
See  <<dsconfig-set-extended-operation-handler-prop-who-am-i-extended-operation-handler>> for the properties of this Extended Operation Handler type.
====

`--set {PROP:VALUE}`::

Assigns a value to a property where PROP is the name of the property and VALUE is the single value to be assigned. Specify the same property multiple times in order to assign more than one value to it.
+
Extended Operation Handler properties depend on the Extended Operation Handler type, which depends on the `--handler-name {name}` option.

`--reset {property}`::

Resets a property back to its default values where PROP is the name of the property to be reset.
+
Extended Operation Handler properties depend on the Extended Operation Handler type, which depends on the `--handler-name {name}` option.

`--add {PROP:VALUE}`::

Adds a single value to a property where PROP is the name of the property and VALUE is the single value to be added.
+
Extended Operation Handler properties depend on the Extended Operation Handler type, which depends on the `--handler-name {name}` option.

`--remove {PROP:VALUE}`::

Removes a single value from a property where PROP is the name of the property and VALUE is the single value to be removed.
+
Extended Operation Handler properties depend on the Extended Operation Handler type, which depends on the `--handler-name {name}` option.

--

[#dsconfig-set-extended-operation-handler-prop-cancel-extended-operation-handler]
== Cancel Extended Operation Handler

Extended Operation Handlers of type cancel-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Cancel Extended Operation Handler implementation. 


Default Value::
org.opends.server.extensions.CancelExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-extended-operation-handler-prop-get-connection-id-extended-operation-handler]
== Get Connection Id Extended Operation Handler

Extended Operation Handlers of type get-connection-id-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Get Connection Id Extended Operation Handler implementation. 


Default Value::
org.opends.server.extensions.GetConnectionIDExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-extended-operation-handler-prop-get-symmetric-key-extended-operation-handler]
== Get Symmetric Key Extended Operation Handler

Extended Operation Handlers of type get-symmetric-key-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Get Symmetric Key Extended Operation Handler implementation. 


Default Value::
org.opends.server.crypto.GetSymmetricKeyExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-extended-operation-handler-prop-password-modify-extended-operation-handler]
== Password Modify Extended Operation Handler

Extended Operation Handlers of type password-modify-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

identity-mapper::
[open]
====
Description::
Specifies the name of the identity mapper that should be used in conjunction with the password modify extended operation. This property is used to identify a user based on an authorization ID in the &apos;u:&apos; form. Changes to this property take effect immediately.


Default Value::
None


Allowed Values::
The DN of any Identity Mapper. The referenced identity mapper must be enabled when the Password Modify Extended Operation Handler is enabled.


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Password Modify Extended Operation Handler implementation. 


Default Value::
org.opends.server.extensions.PasswordModifyExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-extended-operation-handler-prop-password-policy-state-extended-operation-handler]
== Password Policy State Extended Operation Handler

Extended Operation Handlers of type password-policy-state-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Password Policy State Extended Operation Handler implementation. 


Default Value::
org.opends.server.extensions.PasswordPolicyStateExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-extended-operation-handler-prop-start-tls-extended-operation-handler]
== Start TLS Extended Operation Handler

Extended Operation Handlers of type start-tls-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Start TLS Extended Operation Handler implementation. 


Default Value::
org.opends.server.extensions.StartTLSExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-set-extended-operation-handler-prop-who-am-i-extended-operation-handler]
== Who Am I Extended Operation Handler

Extended Operation Handlers of type who-am-i-extended-operation-handler have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Extended Operation Handler is enabled (that is, whether the types of extended operations are allowed in the server). 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Who Am I Extended Operation Handler implementation. 


Default Value::
org.opends.server.extensions.WhoAmIExtendedOperation


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.ExtendedOperationHandler


Multi-valued::
No

Required::
Yes

Admin Action Required::
The Extended Operation Handler must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

