////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2025 3A Systems LLC.
////

[#dsconfig-get-password-storage-scheme-prop]
= dsconfig get-password-storage-scheme-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig get-password-storage-scheme-prop - Shows Password Storage Scheme properties

== Synopsis

`dsconfig get-password-storage-scheme-prop` {options}

[#dsconfig-get-password-storage-scheme-prop-description]
== Description

Shows Password Storage Scheme properties.



[#dsconfig-get-password-storage-scheme-prop-options]
== Options

The `dsconfig get-password-storage-scheme-prop` command takes the following options:

--
`--scheme-name {name}`::

The name of the Password Storage Scheme.
+

[open]
====
Password Storage Scheme properties depend on the Password Storage Scheme type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Password Storage Scheme types:

`aes-password-storage-scheme`::
+
Default {name}: AES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-aes-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`base64-password-storage-scheme`::
+
Default {name}: Base64 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-base64-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`bcrypt-password-storage-scheme`::
+
Default {name}: Bcrypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-bcrypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`blowfish-password-storage-scheme`::
+
Default {name}: Blowfish Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-blowfish-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`clear-password-storage-scheme`::
+
Default {name}: Clear Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-clear-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`crypt-password-storage-scheme`::
+
Default {name}: Crypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-crypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`md5-password-storage-scheme`::
+
Default {name}: MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha256-password-storage-scheme`::
+
Default {name}: PBKDF2 Hmac SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha512-password-storage-scheme`::
+
Default {name}: PBKDF2 Hmac SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pkcs5s2-password-storage-scheme`::
+
Default {name}: PKCS5S2 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pkcs5s2-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`rc4-password-storage-scheme`::
+
Default {name}: RC4 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-rc4-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-md5-password-storage-scheme`::
+
Default {name}: Salted MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha1-password-storage-scheme`::
+
Default {name}: Salted SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha256-password-storage-scheme`::
+
Default {name}: Salted SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha384-password-storage-scheme`::
+
Default {name}: Salted SHA384 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha384-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha512-password-storage-scheme`::
+
Default {name}: Salted SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`sha1-password-storage-scheme`::
+
Default {name}: SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`triple-des-password-storage-scheme`::
+
Default {name}: Triple DES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-triple-des-password-storage-scheme>> for the properties of this Password Storage Scheme type.
====

`--property {property}`::

The name of a property to be displayed.
+

[open]
====
Password Storage Scheme properties depend on the Password Storage Scheme type, which depends on the {property} you provide.

By default, OpenDJ directory server supports the following Password Storage Scheme types:

`aes-password-storage-scheme`::
+
Default {property}: AES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-aes-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`base64-password-storage-scheme`::
+
Default {property}: Base64 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-base64-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`bcrypt-password-storage-scheme`::
+
Default {property}: Bcrypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-bcrypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`blowfish-password-storage-scheme`::
+
Default {property}: Blowfish Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-blowfish-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`clear-password-storage-scheme`::
+
Default {property}: Clear Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-clear-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`crypt-password-storage-scheme`::
+
Default {property}: Crypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-crypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`md5-password-storage-scheme`::
+
Default {property}: MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha256-password-storage-scheme`::
+
Default {property}: PBKDF2 Hmac SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha512-password-storage-scheme`::
+
Default {property}: PBKDF2 Hmac SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pkcs5s2-password-storage-scheme`::
+
Default {property}: PKCS5S2 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pkcs5s2-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`rc4-password-storage-scheme`::
+
Default {property}: RC4 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-rc4-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-md5-password-storage-scheme`::
+
Default {property}: Salted MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha1-password-storage-scheme`::
+
Default {property}: Salted SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha256-password-storage-scheme`::
+
Default {property}: Salted SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha384-password-storage-scheme`::
+
Default {property}: Salted SHA384 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha384-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha512-password-storage-scheme`::
+
Default {property}: Salted SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`sha1-password-storage-scheme`::
+
Default {property}: SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`triple-des-password-storage-scheme`::
+
Default {property}: Triple DES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-triple-des-password-storage-scheme>> for the properties of this Password Storage Scheme type.
====

`-E | --record`::

Modifies the display output to show one property value per line.
+

[open]
====
Password Storage Scheme properties depend on the Password Storage Scheme type, which depends on the null you provide.

By default, OpenDJ directory server supports the following Password Storage Scheme types:

`aes-password-storage-scheme`::
+
Default null: AES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-aes-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`base64-password-storage-scheme`::
+
Default null: Base64 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-base64-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`bcrypt-password-storage-scheme`::
+
Default null: Bcrypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-bcrypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`blowfish-password-storage-scheme`::
+
Default null: Blowfish Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-blowfish-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`clear-password-storage-scheme`::
+
Default null: Clear Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-clear-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`crypt-password-storage-scheme`::
+
Default null: Crypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-crypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`md5-password-storage-scheme`::
+
Default null: MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha256-password-storage-scheme`::
+
Default null: PBKDF2 Hmac SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha512-password-storage-scheme`::
+
Default null: PBKDF2 Hmac SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pkcs5s2-password-storage-scheme`::
+
Default null: PKCS5S2 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pkcs5s2-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`rc4-password-storage-scheme`::
+
Default null: RC4 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-rc4-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-md5-password-storage-scheme`::
+
Default null: Salted MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha1-password-storage-scheme`::
+
Default null: Salted SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha256-password-storage-scheme`::
+
Default null: Salted SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha384-password-storage-scheme`::
+
Default null: Salted SHA384 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha384-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha512-password-storage-scheme`::
+
Default null: Salted SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`sha1-password-storage-scheme`::
+
Default null: SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`triple-des-password-storage-scheme`::
+
Default null: Triple DES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-triple-des-password-storage-scheme>> for the properties of this Password Storage Scheme type.
====

`-z | --unit-size {unit}`::

Display size data using the specified unit. The value for UNIT can be one of b, kb, mb, gb, or tb (bytes, kilobytes, megabytes, gigabytes, or terabytes).
+

[open]
====
Password Storage Scheme properties depend on the Password Storage Scheme type, which depends on the {unit} you provide.

By default, OpenDJ directory server supports the following Password Storage Scheme types:

`aes-password-storage-scheme`::
+
Default {unit}: AES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-aes-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`base64-password-storage-scheme`::
+
Default {unit}: Base64 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-base64-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`bcrypt-password-storage-scheme`::
+
Default {unit}: Bcrypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-bcrypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`blowfish-password-storage-scheme`::
+
Default {unit}: Blowfish Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-blowfish-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`clear-password-storage-scheme`::
+
Default {unit}: Clear Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-clear-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`crypt-password-storage-scheme`::
+
Default {unit}: Crypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-crypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`md5-password-storage-scheme`::
+
Default {unit}: MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha256-password-storage-scheme`::
+
Default {unit}: PBKDF2 Hmac SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha512-password-storage-scheme`::
+
Default {unit}: PBKDF2 Hmac SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pkcs5s2-password-storage-scheme`::
+
Default {unit}: PKCS5S2 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pkcs5s2-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`rc4-password-storage-scheme`::
+
Default {unit}: RC4 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-rc4-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-md5-password-storage-scheme`::
+
Default {unit}: Salted MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha1-password-storage-scheme`::
+
Default {unit}: Salted SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha256-password-storage-scheme`::
+
Default {unit}: Salted SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha384-password-storage-scheme`::
+
Default {unit}: Salted SHA384 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha384-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha512-password-storage-scheme`::
+
Default {unit}: Salted SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`sha1-password-storage-scheme`::
+
Default {unit}: SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`triple-des-password-storage-scheme`::
+
Default {unit}: Triple DES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-triple-des-password-storage-scheme>> for the properties of this Password Storage Scheme type.
====

`-m | --unit-time {unit}`::

Display time data using the specified unit. The value for UNIT can be one of ms, s, m, h, d, or w (milliseconds, seconds, minutes, hours, days, or weeks).
+

[open]
====
Password Storage Scheme properties depend on the Password Storage Scheme type, which depends on the {unit} you provide.

By default, OpenDJ directory server supports the following Password Storage Scheme types:

`aes-password-storage-scheme`::
+
Default {unit}: AES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-aes-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`base64-password-storage-scheme`::
+
Default {unit}: Base64 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-base64-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`bcrypt-password-storage-scheme`::
+
Default {unit}: Bcrypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-bcrypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`blowfish-password-storage-scheme`::
+
Default {unit}: Blowfish Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-blowfish-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`clear-password-storage-scheme`::
+
Default {unit}: Clear Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-clear-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`crypt-password-storage-scheme`::
+
Default {unit}: Crypt Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-crypt-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`md5-password-storage-scheme`::
+
Default {unit}: MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha256-password-storage-scheme`::
+
Default {unit}: PBKDF2 Hmac SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pbkdf2-hmac-sha512-password-storage-scheme`::
+
Default {unit}: PBKDF2 Hmac SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`pkcs5s2-password-storage-scheme`::
+
Default {unit}: PKCS5S2 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-pkcs5s2-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`rc4-password-storage-scheme`::
+
Default {unit}: RC4 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-rc4-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-md5-password-storage-scheme`::
+
Default {unit}: Salted MD5 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-md5-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha1-password-storage-scheme`::
+
Default {unit}: Salted SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha256-password-storage-scheme`::
+
Default {unit}: Salted SHA256 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha256-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha384-password-storage-scheme`::
+
Default {unit}: Salted SHA384 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha384-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`salted-sha512-password-storage-scheme`::
+
Default {unit}: Salted SHA512 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-salted-sha512-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`sha1-password-storage-scheme`::
+
Default {unit}: SHA1 Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-sha1-password-storage-scheme>> for the properties of this Password Storage Scheme type.
`triple-des-password-storage-scheme`::
+
Default {unit}: Triple DES Password Storage Scheme
+
Enabled by default: true
+
See  <<dsconfig-get-password-storage-scheme-prop-triple-des-password-storage-scheme>> for the properties of this Password Storage Scheme type.
====

--

[#dsconfig-get-password-storage-scheme-prop-aes-password-storage-scheme]
== AES Password Storage Scheme

Password Storage Schemes of type aes-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the AES Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.AESPasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-base64-password-storage-scheme]
== Base64 Password Storage Scheme

Password Storage Schemes of type base64-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Base64 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.Base64PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-bcrypt-password-storage-scheme]
== Bcrypt Password Storage Scheme

Password Storage Schemes of type bcrypt-password-storage-scheme have the following properties:

--


bcrypt-cost::
[open]
====
Description::
The cost parameter specifies a key expansion iteration count as a power of two. A default value of 12 (2^12 iterations) is considered in 2016 as a reasonable balance between responsiveness and security for regular users. 


Default Value::
12


Allowed Values::
An integer value. Lower value is 1. Upper value is 30.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Bcrypt Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.BcryptPasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-blowfish-password-storage-scheme]
== Blowfish Password Storage Scheme

Password Storage Schemes of type blowfish-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Blowfish Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.BlowfishPasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-clear-password-storage-scheme]
== Clear Password Storage Scheme

Password Storage Schemes of type clear-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Clear Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.ClearPasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-crypt-password-storage-scheme]
== Crypt Password Storage Scheme

Password Storage Schemes of type crypt-password-storage-scheme have the following properties:

--


crypt-password-storage-encryption-algorithm::
[open]
====
Description::
Specifies the algorithm to use to encrypt new passwords. Select the crypt algorithm to use to encrypt new passwords. The value can either be &quot;unix&quot;, which means the password is encrypted with the weak Unix crypt algorithm, or &quot;md5&quot; which means the password is encrypted with the BSD MD5 algorithm and has a $1$ prefix, or &quot;sha256&quot; which means the password is encrypted with the SHA256 algorithm and has a $5$ prefix, or &quot;sha512&quot; which means the password is encrypted with the SHA512 algorithm and has a $6$ prefix.


Default Value::
unix


Allowed Values::


md5::
New passwords are encrypted with the BSD MD5 algorithm.

sha256::
New passwords are encrypted with the Unix crypt SHA256 algorithm.

sha512::
New passwords are encrypted with the Unix crypt SHA512 algorithm.

unix::
New passwords are encrypted with the Unix crypt algorithm. Passwords are truncated at 8 characters and the top bit of each character is ignored.



Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Crypt Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.CryptPasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-md5-password-storage-scheme]
== MD5 Password Storage Scheme

Password Storage Schemes of type md5-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the MD5 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.MD5PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha256-password-storage-scheme]
== PBKDF2 Hmac SHA256 Password Storage Scheme

Password Storage Schemes of type pbkdf2-hmac-sha256-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the PBKDF2 Hmac SHA256 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.PBKDF2HmacSHA256PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

pbkdf2-iterations::
[open]
====
Description::
The number of algorithm iterations to make. NIST recommends at least 1000. 


Default Value::
10000


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-pbkdf2-hmac-sha512-password-storage-scheme]
== PBKDF2 Hmac SHA512 Password Storage Scheme

Password Storage Schemes of type pbkdf2-hmac-sha512-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the PBKDF2 Hmac SHA512 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.PBKDF2HmacSHA512PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

pbkdf2-iterations::
[open]
====
Description::
The number of algorithm iterations to make. NIST recommends at least 1000. 


Default Value::
10000


Allowed Values::
An integer value. Lower value is 1.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-pkcs5s2-password-storage-scheme]
== PKCS5S2 Password Storage Scheme

Password Storage Schemes of type pkcs5s2-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the PKCS5S2 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.PKCS5S2PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-rc4-password-storage-scheme]
== RC4 Password Storage Scheme

Password Storage Schemes of type rc4-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the RC4 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.RC4PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-salted-md5-password-storage-scheme]
== Salted MD5 Password Storage Scheme

Password Storage Schemes of type salted-md5-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Salted MD5 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.SaltedMD5PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-salted-sha1-password-storage-scheme]
== Salted SHA1 Password Storage Scheme

Password Storage Schemes of type salted-sha1-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Salted SHA1 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.SaltedSHA1PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-salted-sha256-password-storage-scheme]
== Salted SHA256 Password Storage Scheme

Password Storage Schemes of type salted-sha256-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Salted SHA256 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.SaltedSHA256PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-salted-sha384-password-storage-scheme]
== Salted SHA384 Password Storage Scheme

Password Storage Schemes of type salted-sha384-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Salted SHA384 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.SaltedSHA384PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-salted-sha512-password-storage-scheme]
== Salted SHA512 Password Storage Scheme

Password Storage Schemes of type salted-sha512-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Salted SHA512 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.SaltedSHA512PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-sha1-password-storage-scheme]
== SHA1 Password Storage Scheme

Password Storage Schemes of type sha1-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the SHA1 Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.SHA1PasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

[#dsconfig-get-password-storage-scheme-prop-triple-des-password-storage-scheme]
== Triple DES Password Storage Scheme

Password Storage Schemes of type triple-des-password-storage-scheme have the following properties:

--


enabled::
[open]
====
Description::
Indicates whether the Password Storage Scheme is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Triple DES Password Storage Scheme implementation. 


Default Value::
org.opends.server.extensions.TripleDESPasswordStorageScheme


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.PasswordStorageScheme


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

