////
 # The contents of this file are subject to the terms of the Common Development and
 # Distribution License (the License). You may not use this file except in compliance with the
 # License.
 #
 # You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
 # specific language governing permission and limitations under the License.
 #
 # When distributing Covered Software, include this CDDL Header Notice in each file and include
 # the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 # Header, with the fields enclosed by brackets [] replaced by your own identifying
 # information: "Portions Copyright [year] [name of copyright owner]".
 #
 # Copyright 2015 ForgeRock AS.
 # Portions 2024 3A Systems LLC.
 #
////

[#manage-tasks-1]
= manage-tasks(1)

:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
manage-tasks - manage OpenDJ server administration tasks

== Synopsis
`manage-tasks` 

[#manage-tasks-description]
== Description

This utility can be used to obtain a list of tasks scheduled to run within the Directory Server as well as information about individual tasks.




[#manage-tasks-options]
== Options

The `manage-tasks` command takes the following options:

.Command options:

--
`-c | --cancel {taskID}`::
ID of a particular task to cancel.
+

`--connectTimeout {timeout}`::
Maximum length of time (in milliseconds) that can be taken to establish a connection.  Use '0' to specify no time out.
+
Default: 30000
+

`-i | --info {taskID}`::
ID of a particular task about which this tool will display information.
+

`-s | --summary`::
Print a summary of tasks.
+
Default: false
+


--
.LDAP connection options:

--
`-D | --bindDN {bindDN}`::
DN to use to bind to the server.
+
Default: cn=Directory Manager
+

`-h | --hostname {host}`::
The fully-qualified directory server host name that will be used when generating self-signed certificates for LDAP SSL/StartTLS, the administration connector, and replication.
+
Default: localhost.localdomain
+

`-j | --bindPasswordFile {bindPasswordFile}`::
Bind password file.
+

`-K | --keyStorePath {keyStorePath}`::
Certificate key store path.
+

`-N | --certNickname {nickname}`::
Nickname of the certificate that the server should use when accepting SSL-based connections or performing StartTLS negotiation.
+

`-o | --saslOption {name=value}`::
SASL bind options.
+

`-p | --port {port}`::
Directory server administration port number.
+
Default: 4444
+

`-P | --trustStorePath {trustStorePath}`::
Certificate trust store path.
+

`-T | --trustStorePassword {trustStorePassword}`::
Certificate trust store PIN.
+

`-u | --keyStorePasswordFile {keyStorePasswordFile}`::
Certificate key store PIN file.  A PIN is required when you specify to use an existing certificate as server certificate.
+

`-U | --trustStorePasswordFile {path}`::
Certificate trust store PIN file.
+

`-w | --bindPassword {bindPassword}`::
Password to use to bind to the server. Use -w - to ensure that the command prompts for the password, rather than entering the password as a command argument.
+

`-W | --keyStorePassword {keyStorePassword}`::
Certificate key store PIN.  A PIN is required when you specify to use an existing certificate as server certificate.
+

`-X | --trustAll`::
Trust all server SSL certificates.
+
Default: false
+


--
.Utility input/output options:

--
`-n | --no-prompt`::
Use non-interactive mode.  If data in the command is missing, the user is not prompted and the tool will fail.
+
Default: false
+

`--noPropertiesFile`::
No properties file will be used to get default command line argument values.
+
Default: false
+

`--propertiesFilePath {propertiesFilePath}`::
Path to the file containing default property values used for command line arguments.
+


--
.General options:

--
`-V | --version`::
Display Directory Server version information.
+
Default: false
+


--

--
`-H | --help`::
Display this usage information.
+
Default: false
+


--



include::./_exit-codes-0-gt0.adoc[]

include::./_manage-tasks-examples.adoc[]


