////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2024-2026 3A Systems LLC.
////

[#dsconfig-delete-synchronization-provider]
= dsconfig delete-synchronization-provider(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig delete-synchronization-provider - Deletes Synchronization Providers

== Synopsis

`dsconfig delete-synchronization-provider` {options}

[#dsconfig-delete-synchronization-provider-description]
== Description

Deletes Synchronization Providers.



[#dsconfig-delete-synchronization-provider-options]
== Options

The `dsconfig delete-synchronization-provider` command takes the following options:

--
`--provider-name {name}`::

The name of the Synchronization Provider.
+

[open]
====
Synchronization Provider properties depend on the Synchronization Provider type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Synchronization Provider types:

`replication-synchronization-provider`::
+
Default {name}: Replication Synchronization Provider
+
Enabled by default: true
+
See  <<dsconfig-delete-synchronization-provider-replication-synchronization-provider>> for the properties of this Synchronization Provider type.
====

`-f | --force`::

Ignore non-existent Synchronization Providers.
+

[open]
====
Synchronization Provider properties depend on the Synchronization Provider type, which depends on the null you provide.

By default, OpenDJ directory server supports the following Synchronization Provider types:

`replication-synchronization-provider`::
+
Default null: Replication Synchronization Provider
+
Enabled by default: true
+
See  <<dsconfig-delete-synchronization-provider-replication-synchronization-provider>> for the properties of this Synchronization Provider type.
====

--

[#dsconfig-delete-synchronization-provider-replication-synchronization-provider]
== Replication Synchronization Provider

Synchronization Providers of type replication-synchronization-provider have the following properties:

--


connection-timeout::
[open]
====
Description::
Specifies the timeout used when connecting to peers and when performing SSL negotiation. 


Default Value::
5 seconds


Allowed Values::
<xinclude:include href="itemizedlist-duration.xml" />
Lower limit is 0 milliseconds.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the Synchronization Provider is enabled for use. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

java-class::
[open]
====
Description::
Specifies the fully-qualified name of the Java class that provides the Replication Synchronization Provider implementation. 


Default Value::
org.opends.server.replication.plugin.MultimasterReplication


Allowed Values::
A Java class that implements or extends the class(es): org.opends.server.api.SynchronizationProvider


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

num-update-replay-threads::
[open]
====
Description::
Specifies the number of update replay threads. This value is the number of threads created for replaying every updates received for all the replication domains.


Default Value::
Let the server decide.


Allowed Values::
An integer value. Lower value is 1. Upper value is 65535.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====



--

