////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2025 3A Systems LLC.
////

[#dsconfig-get-crypto-manager-prop]
= dsconfig get-crypto-manager-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig get-crypto-manager-prop - Shows Crypto Manager properties

== Synopsis

`dsconfig get-crypto-manager-prop` {options}

[#dsconfig-get-crypto-manager-prop-description]
== Description

Shows Crypto Manager properties.



[#dsconfig-get-crypto-manager-prop-options]
== Options

The `dsconfig get-crypto-manager-prop` command takes the following options:

--
`--property {property}`::

The name of a property to be displayed.
+

[open]
====
Crypto Manager properties depend on the Crypto Manager type, which depends on the {property} you provide.

By default, OpenDJ directory server supports the following Crypto Manager types:

`crypto-manager`::
+
Default {property}: Crypto Manager
+
Enabled by default: false
+
See  <<dsconfig-get-crypto-manager-prop-crypto-manager>> for the properties of this Crypto Manager type.
====

`-E | --record`::

Modifies the display output to show one property value per line.
+

[open]
====
Crypto Manager properties depend on the Crypto Manager type, which depends on the null you provide.

By default, OpenDJ directory server supports the following Crypto Manager types:

`crypto-manager`::
+
Default null: Crypto Manager
+
Enabled by default: false
+
See  <<dsconfig-get-crypto-manager-prop-crypto-manager>> for the properties of this Crypto Manager type.
====

`-z | --unit-size {unit}`::

Display size data using the specified unit. The value for UNIT can be one of b, kb, mb, gb, or tb (bytes, kilobytes, megabytes, gigabytes, or terabytes).
+

[open]
====
Crypto Manager properties depend on the Crypto Manager type, which depends on the {unit} you provide.

By default, OpenDJ directory server supports the following Crypto Manager types:

`crypto-manager`::
+
Default {unit}: Crypto Manager
+
Enabled by default: false
+
See  <<dsconfig-get-crypto-manager-prop-crypto-manager>> for the properties of this Crypto Manager type.
====

`-m | --unit-time {unit}`::

Display time data using the specified unit. The value for UNIT can be one of ms, s, m, h, d, or w (milliseconds, seconds, minutes, hours, days, or weeks).
+

[open]
====
Crypto Manager properties depend on the Crypto Manager type, which depends on the {unit} you provide.

By default, OpenDJ directory server supports the following Crypto Manager types:

`crypto-manager`::
+
Default {unit}: Crypto Manager
+
Enabled by default: false
+
See  <<dsconfig-get-crypto-manager-prop-crypto-manager>> for the properties of this Crypto Manager type.
====

--

[#dsconfig-get-crypto-manager-prop-crypto-manager]
== Crypto Manager

Crypto Managers of type crypto-manager have the following properties:

--


cipher-key-length::
[open]
====
Description::
Specifies the key length in bits for the preferred cipher. 


Default Value::
128


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

cipher-transformation::
[open]
====
Description::
Specifies the cipher for the directory server using the syntax algorithm/mode/padding. The full transformation is required: specifying only an algorithm and allowing the cipher provider to supply the default mode and padding is not supported, because there is no guarantee these default values are the same among different implementations. Some cipher algorithms, including RC4 and ARCFOUR, do not have a mode or padding, and hence must be specified using NONE for the mode field and NoPadding for the padding field. For example, RC4/NONE/NoPadding.


Default Value::
AES/CBC/PKCS5Padding


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

digest-algorithm::
[open]
====
Description::
Specifies the preferred message digest algorithm for the directory server. 


Default Value::
SHA-256


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately and only affect cryptographic operations performed after the change.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

key-wrapping-transformation::
[open]
====
Description::
The preferred key wrapping transformation for the directory server. This value must be the same for all server instances in a replication topology. 


Default Value::
RSA/ECB/OAEPWITHSHA-1ANDMGF1PADDING


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property will take effect immediately but will only affect cryptographic operations performed after the change.

Advanced Property::
No

Read-only::
No


====

mac-algorithm::
[open]
====
Description::
Specifies the preferred MAC algorithm for the directory server. 


Default Value::
HmacSHA256


Allowed Values::
A String


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

mac-key-length::
[open]
====
Description::
Specifies the key length in bits for the preferred MAC algorithm. 


Default Value::
128


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only affect cryptographic operations performed after the change.

Advanced Property::
Yes (Use --advanced in interactive mode.)

Read-only::
No


====

ssl-cert-nickname::
[open]
====
Description::
Specifies the nicknames (also called the aliases) of the keys or key pairs that the Crypto Manager should use when performing SSL communication. The property can be used multiple times (referencing different nicknames) when server certificates with different public key algorithms are used in parallel (for example, RSA, DSA, and ECC-based algorithms). When a nickname refers to an asymmetric (public/private) key pair, the nickname for the public key certificate and associated private key entry must match exactly. A single nickname is used to retrieve both the public key and the private key. This is only applicable when the Crypto Manager is configured to use SSL.


Default Value::
Let the server decide.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
The Crypto Manager must be disabled and re-enabled for changes to this setting to take effect

Advanced Property::
No

Read-only::
No


====

ssl-cipher-suite::
[open]
====
Description::
Specifies the names of the SSL cipher suites that are allowed for use in SSL or TLS communication. 


Default Value::
Uses the default set of SSL cipher suites provided by the server's JVM.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only impact new SSL/TLS-based sessions created after the change.

Advanced Property::
No

Read-only::
No


====

ssl-encryption::
[open]
====
Description::
Specifies whether SSL/TLS is used to provide encrypted communication between two OpenDJ server components. 


Default Value::
false


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only impact new SSL/TLS-based sessions created after the change.

Advanced Property::
No

Read-only::
No


====

ssl-protocol::
[open]
====
Description::
Specifies the names of the SSL protocols that are allowed for use in SSL or TLS communication. 


Default Value::
Uses the default set of SSL protocols provided by the server's JVM.


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
NoneChanges to this property take effect immediately but only impact new SSL/TLS-based sessions created after the change.

Advanced Property::
No

Read-only::
No


====



--

