////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2024-2025 3A Systems LLC.
////

[#dsconfig-set-access-log-filtering-criteria-prop]
= dsconfig set-access-log-filtering-criteria-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig set-access-log-filtering-criteria-prop - Modifies Access Log Filtering Criteria properties

== Synopsis

`dsconfig set-access-log-filtering-criteria-prop` {options}

[#dsconfig-set-access-log-filtering-criteria-prop-description]
== Description

Modifies Access Log Filtering Criteria properties.



[#dsconfig-set-access-log-filtering-criteria-prop-options]
== Options

The `dsconfig set-access-log-filtering-criteria-prop` command takes the following options:

--
`--publisher-name {name}`::

The name of the Access Log Publisher.
+

[open]
====
Access Log Filtering Criteria properties depend on the Access Log Filtering Criteria type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Access Log Filtering Criteria types:

`access-log-filtering-criteria`::
+
Default {name}: Access Log Filtering Criteria
+
Enabled by default: false
+
See  <<dsconfig-set-access-log-filtering-criteria-prop-access-log-filtering-criteria>> for the properties of this Access Log Filtering Criteria type.
====

`--criteria-name {name}`::

The name of the Access Log Filtering Criteria.
+

[open]
====
Access Log Filtering Criteria properties depend on the Access Log Filtering Criteria type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following Access Log Filtering Criteria types:

`access-log-filtering-criteria`::
+
Default {name}: Access Log Filtering Criteria
+
Enabled by default: false
+
See  <<dsconfig-set-access-log-filtering-criteria-prop-access-log-filtering-criteria>> for the properties of this Access Log Filtering Criteria type.
====

`--set {PROP:VALUE}`::

Assigns a value to a property where PROP is the name of the property and VALUE is the single value to be assigned. Specify the same property multiple times in order to assign more than one value to it.
+
Access Log Filtering Criteria properties depend on the Access Log Filtering Criteria type, which depends on the `--criteria-name {name}` option.

`--reset {property}`::

Resets a property back to its default values where PROP is the name of the property to be reset.
+
Access Log Filtering Criteria properties depend on the Access Log Filtering Criteria type, which depends on the `--criteria-name {name}` option.

`--add {PROP:VALUE}`::

Adds a single value to a property where PROP is the name of the property and VALUE is the single value to be added.
+
Access Log Filtering Criteria properties depend on the Access Log Filtering Criteria type, which depends on the `--criteria-name {name}` option.

`--remove {PROP:VALUE}`::

Removes a single value from a property where PROP is the name of the property and VALUE is the single value to be removed.
+
Access Log Filtering Criteria properties depend on the Access Log Filtering Criteria type, which depends on the `--criteria-name {name}` option.

--

[#dsconfig-set-access-log-filtering-criteria-prop-access-log-filtering-criteria]
== Access Log Filtering Criteria

Access Log Filtering Criteria of type access-log-filtering-criteria have the following properties:

--


connection-client-address-equal-to::
[open]
====
Description::
Filters log records associated with connections which match at least one of the specified client host names or address masks. Valid values include a host name, a fully qualified domain name, a domain name, an IP address, or a subnetwork with subnetwork mask.


Default Value::
None


Allowed Values::
An IP address mask


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

connection-client-address-not-equal-to::
[open]
====
Description::
Filters log records associated with connections which do not match any of the specified client host names or address masks. Valid values include a host name, a fully qualified domain name, a domain name, an IP address, or a subnetwork with subnetwork mask.


Default Value::
None


Allowed Values::
An IP address mask


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

connection-port-equal-to::
[open]
====
Description::
Filters log records associated with connections to any of the specified listener port numbers. 


Default Value::
None


Allowed Values::
An integer value. Lower value is 1. Upper value is 65535.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

connection-protocol-equal-to::
[open]
====
Description::
Filters log records associated with connections which match any of the specified protocols. Typical values include &quot;ldap&quot;, &quot;ldaps&quot;, or &quot;jmx&quot;.


Default Value::
None


Allowed Values::
The protocol name as reported in the access log.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

log-record-type::
[open]
====
Description::
Filters log records based on their type. 


Default Value::
None


Allowed Values::


abandon::
Abandon operations

add::
Add operations

bind::
Bind operations

compare::
Compare operations

connect::
Client connections

delete::
Delete operations

disconnect::
Client disconnections

extended::
Extended operations

modify::
Modify operations

rename::
Rename operations

search::
Search operations

unbind::
Unbind operations



Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

request-target-dn-equal-to::
[open]
====
Description::
Filters operation log records associated with operations which target entries matching at least one of the specified DN patterns. Valid DN filters are strings composed of zero or more wildcards. A double wildcard ** replaces one or more RDN components (as in uid=dmiller,**,dc=example,dc=com). A simple wildcard * replaces either a whole RDN, or a whole type, or a value substring (as in uid=bj*,ou=people,dc=example,dc=com).


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

request-target-dn-not-equal-to::
[open]
====
Description::
Filters operation log records associated with operations which target entries matching none of the specified DN patterns. Valid DN filters are strings composed of zero or more wildcards. A double wildcard ** replaces one or more RDN components (as in uid=dmiller,**,dc=example,dc=com). A simple wildcard * replaces either a whole RDN, or a whole type, or a value substring (as in uid=bj*,ou=people,dc=example,dc=com).


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

response-etime-greater-than::
[open]
====
Description::
Filters operation response log records associated with operations which took longer than the specified number of milli-seconds to complete. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

response-etime-less-than::
[open]
====
Description::
Filters operation response log records associated with operations which took less than the specified number of milli-seconds to complete. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

response-result-code-equal-to::
[open]
====
Description::
Filters operation response log records associated with operations which include any of the specified result codes. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

response-result-code-not-equal-to::
[open]
====
Description::
Filters operation response log records associated with operations which do not include any of the specified result codes. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

search-response-is-indexed::
[open]
====
Description::
Filters search operation response log records associated with searches which were either indexed or unindexed. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

search-response-nentries-greater-than::
[open]
====
Description::
Filters search operation response log records associated with searches which returned more than the specified number of entries. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

search-response-nentries-less-than::
[open]
====
Description::
Filters search operation response log records associated with searches which returned less than the specified number of entries. It is recommended to only use this criteria in conjunction with the &quot;combined&quot; output mode of the access logger, since this filter criteria is only applied to response log messages.


Default Value::
None


Allowed Values::
An integer value. Lower value is 0.


Multi-valued::
No

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

user-dn-equal-to::
[open]
====
Description::
Filters log records associated with users matching at least one of the specified DN patterns. Valid DN filters are strings composed of zero or more wildcards. A double wildcard ** replaces one or more RDN components (as in uid=dmiller,**,dc=example,dc=com). A simple wildcard * replaces either a whole RDN, or a whole type, or a value substring (as in uid=bj*,ou=people,dc=example,dc=com).


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

user-dn-not-equal-to::
[open]
====
Description::
Filters log records associated with users which do not match any of the specified DN patterns. Valid DN filters are strings composed of zero or more wildcards. A double wildcard ** replaces one or more RDN components (as in uid=dmiller,**,dc=example,dc=com). A simple wildcard * replaces either a whole RDN, or a whole type, or a value substring (as in uid=bj*,ou=people,dc=example,dc=com).


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

user-is-member-of::
[open]
====
Description::
Filters log records associated with users which are members of at least one of the specified groups. 


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

user-is-not-member-of::
[open]
====
Description::
Filters log records associated with users which are not members of any of the specified groups. 


Default Value::
None


Allowed Values::
A valid DN.


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

