////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2011-2017 ForgeRock AS.
  Portions Copyright 2025 3A Systems LLC.
////

[#dsconfig-get-external-changelog-domain-prop]
= dsconfig get-external-changelog-domain-prop(1)
:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
dsconfig get-external-changelog-domain-prop - Shows External Changelog Domain properties

== Synopsis

`dsconfig get-external-changelog-domain-prop` {options}

[#dsconfig-get-external-changelog-domain-prop-description]
== Description

Shows External Changelog Domain properties.



[#dsconfig-get-external-changelog-domain-prop-options]
== Options

The `dsconfig get-external-changelog-domain-prop` command takes the following options:

--
`--provider-name {name}`::

The name of the Replication Synchronization Provider.
+

[open]
====
External Changelog Domain properties depend on the External Changelog Domain type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following External Changelog Domain types:

`external-changelog-domain`::
+
Default {name}: External Changelog Domain
+
Enabled by default: true
+
See  <<dsconfig-get-external-changelog-domain-prop-external-changelog-domain>> for the properties of this External Changelog Domain type.
====

`--domain-name {name}`::

The name of the Replication Domain.
+

[open]
====
External Changelog Domain properties depend on the External Changelog Domain type, which depends on the {name} you provide.

By default, OpenDJ directory server supports the following External Changelog Domain types:

`external-changelog-domain`::
+
Default {name}: External Changelog Domain
+
Enabled by default: true
+
See  <<dsconfig-get-external-changelog-domain-prop-external-changelog-domain>> for the properties of this External Changelog Domain type.
====

`--property {property}`::

The name of a property to be displayed.
+

[open]
====
External Changelog Domain properties depend on the External Changelog Domain type, which depends on the {property} you provide.

By default, OpenDJ directory server supports the following External Changelog Domain types:

`external-changelog-domain`::
+
Default {property}: External Changelog Domain
+
Enabled by default: true
+
See  <<dsconfig-get-external-changelog-domain-prop-external-changelog-domain>> for the properties of this External Changelog Domain type.
====

`-E | --record`::

Modifies the display output to show one property value per line.
+

[open]
====
External Changelog Domain properties depend on the External Changelog Domain type, which depends on the null you provide.

By default, OpenDJ directory server supports the following External Changelog Domain types:

`external-changelog-domain`::
+
Default null: External Changelog Domain
+
Enabled by default: true
+
See  <<dsconfig-get-external-changelog-domain-prop-external-changelog-domain>> for the properties of this External Changelog Domain type.
====

`-z | --unit-size {unit}`::

Display size data using the specified unit. The value for UNIT can be one of b, kb, mb, gb, or tb (bytes, kilobytes, megabytes, gigabytes, or terabytes).
+

[open]
====
External Changelog Domain properties depend on the External Changelog Domain type, which depends on the {unit} you provide.

By default, OpenDJ directory server supports the following External Changelog Domain types:

`external-changelog-domain`::
+
Default {unit}: External Changelog Domain
+
Enabled by default: true
+
See  <<dsconfig-get-external-changelog-domain-prop-external-changelog-domain>> for the properties of this External Changelog Domain type.
====

`-m | --unit-time {unit}`::

Display time data using the specified unit. The value for UNIT can be one of ms, s, m, h, d, or w (milliseconds, seconds, minutes, hours, days, or weeks).
+

[open]
====
External Changelog Domain properties depend on the External Changelog Domain type, which depends on the {unit} you provide.

By default, OpenDJ directory server supports the following External Changelog Domain types:

`external-changelog-domain`::
+
Default {unit}: External Changelog Domain
+
Enabled by default: true
+
See  <<dsconfig-get-external-changelog-domain-prop-external-changelog-domain>> for the properties of this External Changelog Domain type.
====

--

[#dsconfig-get-external-changelog-domain-prop-external-changelog-domain]
== External Changelog Domain

External Changelog Domains of type external-changelog-domain have the following properties:

--


ecl-include::
[open]
====
Description::
Specifies a list of attributes which should be published with every change log entry, regardless of whether the attribute itself has changed. The list of attributes may include wild cards such as &quot;*&quot; and &quot;+&quot; as well as object class references prefixed with an ampersand, for example &quot;@person&quot;. The included attributes will be published using the &quot;includedAttributes&quot; operational attribute as a single LDIF value rather like the &quot;changes&quot; attribute. For modify and modifyDN operations the included attributes will be taken from the entry before any changes were applied.


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

ecl-include-for-deletes::
[open]
====
Description::
Specifies a list of attributes which should be published with every delete operation change log entry, in addition to those specified by the &quot;ecl-include&quot; property. This property provides a means for applications to archive entries after they have been deleted. See the description of the &quot;ecl-include&quot; property for further information about how the included attributes are published.


Default Value::
None


Allowed Values::
A String


Multi-valued::
Yes

Required::
No

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====

enabled::
[open]
====
Description::
Indicates whether the External Changelog Domain is enabled. To enable computing the change numbers, set the Replication Server&apos;s &quot;ds-cfg-compute-change-number&quot; property to true. 


Default Value::
None


Allowed Values::
true
false


Multi-valued::
No

Required::
Yes

Admin Action Required::
None

Advanced Property::
No

Read-only::
No


====



--

