////
 # The contents of this file are subject to the terms of the Common Development and
 # Distribution License (the License). You may not use this file except in compliance with the
 # License.
 #
 # You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
 # specific language governing permission and limitations under the License.
 #
 # When distributing Covered Software, include this CDDL Header Notice in each file and include
 # the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 # Header, with the fields enclosed by brackets [] replaced by your own identifying
 # information: "Portions Copyright [year] [name of copyright owner]".
 #
 # Copyright 2015 ForgeRock AS.
 # Portions Copyright 2024-2026 3A Systems LLC.
 #
////

[#encode-password-1]
= encode-password(1)

:doctype: manpage
:manmanual: Directory Server Tools
:mansource: OpenDJ

== Name
encode-password - encode a password with an OpenDJ storage scheme

== Synopsis
`encode-password` 

[#encode-password-description]
== Description

This utility can be used to encode user passwords with a specified storage scheme, or to determine whether a given clear-text value matches a provided encoded password.




[#encode-password-options]
== Options

The `encode-password` command takes the following options:

.Command options:

--
`-a | --authPasswordSyntax`::
Use the authentication password syntax rather than the user password syntax.
+
Default: false
+

`-c | --clearPassword {clearPW}`::
Clear-text password to encode or to compare against an encoded password.
+

`-e | --encodedPassword {encodedPW}`::
Encoded password to compare against the clear-text password.
+

`-E | --encodedPasswordFile {file}`::
Encoded password file.
+

`-f | --clearPasswordFile {file}`::
Clear-text password file.
+

`-i | --interactivePassword`::
The password to encode or to compare against an encoded password is interactively asked to the user.
+
Default: false
+

`-l | --listSchemes`::
List available password storage schemes.
+
Default: false
+

`-r | --useCompareResultCode`::
Use the LDAP compare result as an exit code for the password comparison.
+
Default: false
+

`-s | --storageScheme {scheme}`::
Scheme to use for the encoded password.
+


--
.General options:

--
`-V | --version`::
Display Directory Server version information.
+
Default: false
+


--

--
`-H | --help`::
Display this usage information.
+
Default: false
+


--



include::./_exit-codes-0-5-6-other.adoc[]

include::./_encode-password-examples.adoc[]


