////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

= Samples Guide
:doctype: book
:toc:
:authors: Lana Frost, Mike Jang
:copyright: Copyright 2011-2016 ForgeRock AS.
:copyright: Portions Copyright 2024 3A Systems LLC.

:imagesdir: ../
:figure-caption!:
:example-caption!:
:table-caption!:
[abstract]
This guide provides a number of "sample deployments" that walk you through the essential OpenIDM features, as they would be implemented.

* xref:preface.adoc[]
* xref:chap-overview.adoc[]
* xref:chap-xml-samples.adoc[]
* xref:chap-ldap-samples.adoc[]
* xref:chap-groovy-samples.adoc[]
* xref:chap-powershell-samples.adoc[]
* xref:chap-audit-sample.adoc[]
* xref:chap-roles-sample.adoc[]
* xref:chap-multiaccount-sample.adoc[]
* xref:chap-trustedfilter-sample.adoc[]
* xref:chap-fullstack-sample.adoc[]
* xref:chap-workflow-samples.adoc[]
* xref:chap-google-sample.adoc[]
* xref:chap-salesforce-sample.adoc[]
* xref:chap-kerberos-sample.adoc[]
* xref:chap-endpoint-sample.adoc[]
* xref:openidm-glossary.adoc[]
